//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for client-bind-info complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="client-bind-info">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="flow-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="durable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="bind-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="session-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "client-bind-info", propOrder = {

})
public class ClientBindInfo {

    @XmlElement(name = "flow-id")
    @XmlSchemaType(name = "unsignedInt")
    protected long flowId;
    protected String name;
    protected String type;
    protected Boolean durable;
    @XmlElement(name = "bind-time")
    protected String bindTime;
    @XmlElement(name = "session-name")
    protected String sessionName;

    /**
     * Gets the value of the flowId property.
     */
    public long getFlowId() {
        return flowId;
    }

    /**
     * Sets the value of the flowId property.
     */
    public void setFlowId(long value) {
        this.flowId = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the durable property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isDurable() {
        return durable;
    }

    /**
     * Sets the value of the durable property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDurable(Boolean value) {
        this.durable = value;
    }

    /**
     * Gets the value of the bindTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBindTime() {
        return bindTime;
    }

    /**
     * Sets the value of the bindTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBindTime(String value) {
        this.bindTime = value;
    }

    /**
     * Gets the value of the sessionName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSessionName() {
        return sessionName;
    }

    /**
     * Sets the value of the sessionName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSessionName(String value) {
        this.sessionName = value;
    }

}
