//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for kerberos-keytab-entry complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="kerberos-keytab-entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="index" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="kvno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="principal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="encryption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "kerberos-keytab-entry", propOrder = {

})
public class KerberosKeytabEntry {

    @XmlElement(required = true)
    protected String index;
    @XmlElement(required = true)
    protected String kvno;
    @XmlElement(required = true)
    protected String principal;
    protected String timestamp;
    protected String encryption;

    /**
     * Gets the value of the index property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIndex(String value) {
        this.index = value;
    }

    /**
     * Gets the value of the kvno property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getKvno() {
        return kvno;
    }

    /**
     * Sets the value of the kvno property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKvno(String value) {
        this.kvno = value;
    }

    /**
     * Gets the value of the principal property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * Sets the value of the principal property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrincipal(String value) {
        this.principal = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the encryption property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEncryption() {
        return encryption;
    }

    /**
     * Sets the value of the encryption property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEncryption(String value) {
        this.encryption = value;
    }

}
