//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ldap-profile-stats-type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ldap-profile-stats-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ok" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="encoding-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="out-of-memory" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="server-down" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="decoding-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="no-such-object" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="timeout" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="filter-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="multiple-entries" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="invalid-syntax" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="referral" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="referral-limit-exceeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="invalid-credentials" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="start-tls-failed" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="local-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="operations-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="auth-method-not-supported" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="protocol-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="parameter-error" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="peer-disconnect" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="not-supported" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="other" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ldap-profile-stats-type", propOrder = {

})
public class LdapProfileStatsType {

    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger ok;
    @XmlElement(name = "encoding-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger encodingError;
    @XmlElement(name = "out-of-memory")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger outOfMemory;
    @XmlElement(name = "server-down")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger serverDown;
    @XmlElement(name = "decoding-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger decodingError;
    @XmlElement(name = "no-such-object")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger noSuchObject;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger timeout;
    @XmlElement(name = "filter-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger filterError;
    @XmlElement(name = "multiple-entries")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger multipleEntries;
    @XmlElement(name = "invalid-syntax")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger invalidSyntax;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger referral;
    @XmlElement(name = "referral-limit-exceeded")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger referralLimitExceeded;
    @XmlElement(name = "invalid-credentials")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger invalidCredentials;
    @XmlElement(name = "start-tls-failed")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger startTlsFailed;
    @XmlElement(name = "local-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger localError;
    @XmlElement(name = "operations-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger operationsError;
    @XmlElement(name = "auth-method-not-supported")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger authMethodNotSupported;
    @XmlElement(name = "protocol-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger protocolError;
    @XmlElement(name = "parameter-error")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger parameterError;
    @XmlElement(name = "peer-disconnect")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger peerDisconnect;
    @XmlElement(name = "not-supported")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger notSupported;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger other;

    /**
     * Gets the value of the ok property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getOk() {
        return ok;
    }

    /**
     * Sets the value of the ok property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setOk(BigInteger value) {
        this.ok = value;
    }

    /**
     * Gets the value of the encodingError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getEncodingError() {
        return encodingError;
    }

    /**
     * Sets the value of the encodingError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setEncodingError(BigInteger value) {
        this.encodingError = value;
    }

    /**
     * Gets the value of the outOfMemory property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getOutOfMemory() {
        return outOfMemory;
    }

    /**
     * Sets the value of the outOfMemory property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setOutOfMemory(BigInteger value) {
        this.outOfMemory = value;
    }

    /**
     * Gets the value of the serverDown property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getServerDown() {
        return serverDown;
    }

    /**
     * Sets the value of the serverDown property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setServerDown(BigInteger value) {
        this.serverDown = value;
    }

    /**
     * Gets the value of the decodingError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getDecodingError() {
        return decodingError;
    }

    /**
     * Sets the value of the decodingError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setDecodingError(BigInteger value) {
        this.decodingError = value;
    }

    /**
     * Gets the value of the noSuchObject property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNoSuchObject() {
        return noSuchObject;
    }

    /**
     * Sets the value of the noSuchObject property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNoSuchObject(BigInteger value) {
        this.noSuchObject = value;
    }

    /**
     * Gets the value of the timeout property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getTimeout() {
        return timeout;
    }

    /**
     * Sets the value of the timeout property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setTimeout(BigInteger value) {
        this.timeout = value;
    }

    /**
     * Gets the value of the filterError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getFilterError() {
        return filterError;
    }

    /**
     * Sets the value of the filterError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setFilterError(BigInteger value) {
        this.filterError = value;
    }

    /**
     * Gets the value of the multipleEntries property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMultipleEntries() {
        return multipleEntries;
    }

    /**
     * Sets the value of the multipleEntries property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMultipleEntries(BigInteger value) {
        this.multipleEntries = value;
    }

    /**
     * Gets the value of the invalidSyntax property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getInvalidSyntax() {
        return invalidSyntax;
    }

    /**
     * Sets the value of the invalidSyntax property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setInvalidSyntax(BigInteger value) {
        this.invalidSyntax = value;
    }

    /**
     * Gets the value of the referral property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReferral() {
        return referral;
    }

    /**
     * Sets the value of the referral property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReferral(BigInteger value) {
        this.referral = value;
    }

    /**
     * Gets the value of the referralLimitExceeded property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReferralLimitExceeded() {
        return referralLimitExceeded;
    }

    /**
     * Sets the value of the referralLimitExceeded property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReferralLimitExceeded(BigInteger value) {
        this.referralLimitExceeded = value;
    }

    /**
     * Gets the value of the invalidCredentials property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getInvalidCredentials() {
        return invalidCredentials;
    }

    /**
     * Sets the value of the invalidCredentials property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setInvalidCredentials(BigInteger value) {
        this.invalidCredentials = value;
    }

    /**
     * Gets the value of the startTlsFailed property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getStartTlsFailed() {
        return startTlsFailed;
    }

    /**
     * Sets the value of the startTlsFailed property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setStartTlsFailed(BigInteger value) {
        this.startTlsFailed = value;
    }

    /**
     * Gets the value of the localError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getLocalError() {
        return localError;
    }

    /**
     * Sets the value of the localError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setLocalError(BigInteger value) {
        this.localError = value;
    }

    /**
     * Gets the value of the operationsError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getOperationsError() {
        return operationsError;
    }

    /**
     * Sets the value of the operationsError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setOperationsError(BigInteger value) {
        this.operationsError = value;
    }

    /**
     * Gets the value of the authMethodNotSupported property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getAuthMethodNotSupported() {
        return authMethodNotSupported;
    }

    /**
     * Sets the value of the authMethodNotSupported property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setAuthMethodNotSupported(BigInteger value) {
        this.authMethodNotSupported = value;
    }

    /**
     * Gets the value of the protocolError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getProtocolError() {
        return protocolError;
    }

    /**
     * Sets the value of the protocolError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setProtocolError(BigInteger value) {
        this.protocolError = value;
    }

    /**
     * Gets the value of the parameterError property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getParameterError() {
        return parameterError;
    }

    /**
     * Sets the value of the parameterError property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setParameterError(BigInteger value) {
        this.parameterError = value;
    }

    /**
     * Gets the value of the peerDisconnect property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getPeerDisconnect() {
        return peerDisconnect;
    }

    /**
     * Sets the value of the peerDisconnect property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setPeerDisconnect(BigInteger value) {
        this.peerDisconnect = value;
    }

    /**
     * Gets the value of the notSupported property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNotSupported() {
        return notSupported;
    }

    /**
     * Sets the value of the notSupported property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNotSupported(BigInteger value) {
        this.notSupported = value;
    }

    /**
     * Gets the value of the other property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setOther(BigInteger value) {
        this.other = value;
    }

}
