//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for message-spool-config-info-type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="message-spool-config-info-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="threshold">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="set-percentage">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="clear-percentage">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "message-spool-config-info-type", propOrder = {
        "quota",
        "threshold"
})
public class MessageSpoolConfigInfoType {

    protected double quota;
    @XmlElement(required = true)
    protected MessageSpoolConfigInfoType.Threshold threshold;

    /**
     * Gets the value of the quota property.
     */
    public double getQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     */
    public void setQuota(double value) {
        this.quota = value;
    }

    /**
     * Gets the value of the threshold property.
     *
     * @return possible object is
     * {@link MessageSpoolConfigInfoType.Threshold }
     */
    public MessageSpoolConfigInfoType.Threshold getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     *
     * @param value allowed object is
     *              {@link MessageSpoolConfigInfoType.Threshold }
     */
    public void setThreshold(MessageSpoolConfigInfoType.Threshold value) {
        this.threshold = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="set-percentage">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="clear-percentage">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "setPercentage",
            "clearPercentage"
    })
    public static class Threshold {

        @XmlElement(name = "set-percentage", required = true)
        protected BigInteger setPercentage;
        @XmlElement(name = "clear-percentage", required = true)
        protected BigInteger clearPercentage;

        /**
         * Gets the value of the setPercentage property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getSetPercentage() {
            return setPercentage;
        }

        /**
         * Sets the value of the setPercentage property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setSetPercentage(BigInteger value) {
            this.setPercentage = value;
        }

        /**
         * Gets the value of the clearPercentage property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getClearPercentage() {
            return clearPercentage;
        }

        /**
         * Sets the value of the clearPercentage property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setClearPercentage(BigInteger value) {
            this.clearPercentage = value;
        }

    }

}
