//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mqtt-connection-stats complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="mqtt-connection-stats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="mqtt-connect-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-connack-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-connack-sent-err" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-rcvd-qos0" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-rcvd-qos1" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-rcvd-qos2" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-sent-qos0" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-sent-qos1" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-publish-sent-unformattable" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-puback-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-puback-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-pubrec-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-pubrel-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-pubcomp-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-subscribe-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-suback-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-suback-sent-err" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-unsubscribe-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-unsuback-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-pingreq-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-pingresp-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="mqtt-disconnect-sent" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mqtt-connection-stats", propOrder = {

})
public class MqttConnectionStats {

    @XmlElement(name = "mqtt-connect-rcvd")
    protected long mqttConnectRcvd;
    @XmlElement(name = "mqtt-connack-sent")
    protected long mqttConnackSent;
    @XmlElement(name = "mqtt-connack-sent-err")
    protected long mqttConnackSentErr;
    @XmlElement(name = "mqtt-publish-rcvd-qos0")
    protected long mqttPublishRcvdQos0;
    @XmlElement(name = "mqtt-publish-rcvd-qos1")
    protected long mqttPublishRcvdQos1;
    @XmlElement(name = "mqtt-publish-rcvd-qos2")
    protected long mqttPublishRcvdQos2;
    @XmlElement(name = "mqtt-publish-sent-qos0")
    protected long mqttPublishSentQos0;
    @XmlElement(name = "mqtt-publish-sent-qos1")
    protected long mqttPublishSentQos1;
    @XmlElement(name = "mqtt-publish-sent-unformattable")
    protected long mqttPublishSentUnformattable;
    @XmlElement(name = "mqtt-puback-rcvd")
    protected long mqttPubackRcvd;
    @XmlElement(name = "mqtt-puback-sent")
    protected long mqttPubackSent;
    @XmlElement(name = "mqtt-pubrec-sent")
    protected long mqttPubrecSent;
    @XmlElement(name = "mqtt-pubrel-rcvd")
    protected long mqttPubrelRcvd;
    @XmlElement(name = "mqtt-pubcomp-sent")
    protected long mqttPubcompSent;
    @XmlElement(name = "mqtt-subscribe-rcvd")
    protected long mqttSubscribeRcvd;
    @XmlElement(name = "mqtt-suback-sent")
    protected long mqttSubackSent;
    @XmlElement(name = "mqtt-suback-sent-err")
    protected long mqttSubackSentErr;
    @XmlElement(name = "mqtt-unsubscribe-rcvd")
    protected long mqttUnsubscribeRcvd;
    @XmlElement(name = "mqtt-unsuback-sent")
    protected long mqttUnsubackSent;
    @XmlElement(name = "mqtt-pingreq-rcvd")
    protected long mqttPingreqRcvd;
    @XmlElement(name = "mqtt-pingresp-sent")
    protected long mqttPingrespSent;
    @XmlElement(name = "mqtt-disconnect-sent")
    protected long mqttDisconnectSent;

    /**
     * Gets the value of the mqttConnectRcvd property.
     */
    public long getMqttConnectRcvd() {
        return mqttConnectRcvd;
    }

    /**
     * Sets the value of the mqttConnectRcvd property.
     */
    public void setMqttConnectRcvd(long value) {
        this.mqttConnectRcvd = value;
    }

    /**
     * Gets the value of the mqttConnackSent property.
     */
    public long getMqttConnackSent() {
        return mqttConnackSent;
    }

    /**
     * Sets the value of the mqttConnackSent property.
     */
    public void setMqttConnackSent(long value) {
        this.mqttConnackSent = value;
    }

    /**
     * Gets the value of the mqttConnackSentErr property.
     */
    public long getMqttConnackSentErr() {
        return mqttConnackSentErr;
    }

    /**
     * Sets the value of the mqttConnackSentErr property.
     */
    public void setMqttConnackSentErr(long value) {
        this.mqttConnackSentErr = value;
    }

    /**
     * Gets the value of the mqttPublishRcvdQos0 property.
     */
    public long getMqttPublishRcvdQos0() {
        return mqttPublishRcvdQos0;
    }

    /**
     * Sets the value of the mqttPublishRcvdQos0 property.
     */
    public void setMqttPublishRcvdQos0(long value) {
        this.mqttPublishRcvdQos0 = value;
    }

    /**
     * Gets the value of the mqttPublishRcvdQos1 property.
     */
    public long getMqttPublishRcvdQos1() {
        return mqttPublishRcvdQos1;
    }

    /**
     * Sets the value of the mqttPublishRcvdQos1 property.
     */
    public void setMqttPublishRcvdQos1(long value) {
        this.mqttPublishRcvdQos1 = value;
    }

    /**
     * Gets the value of the mqttPublishRcvdQos2 property.
     */
    public long getMqttPublishRcvdQos2() {
        return mqttPublishRcvdQos2;
    }

    /**
     * Sets the value of the mqttPublishRcvdQos2 property.
     */
    public void setMqttPublishRcvdQos2(long value) {
        this.mqttPublishRcvdQos2 = value;
    }

    /**
     * Gets the value of the mqttPublishSentQos0 property.
     */
    public long getMqttPublishSentQos0() {
        return mqttPublishSentQos0;
    }

    /**
     * Sets the value of the mqttPublishSentQos0 property.
     */
    public void setMqttPublishSentQos0(long value) {
        this.mqttPublishSentQos0 = value;
    }

    /**
     * Gets the value of the mqttPublishSentQos1 property.
     */
    public long getMqttPublishSentQos1() {
        return mqttPublishSentQos1;
    }

    /**
     * Sets the value of the mqttPublishSentQos1 property.
     */
    public void setMqttPublishSentQos1(long value) {
        this.mqttPublishSentQos1 = value;
    }

    /**
     * Gets the value of the mqttPublishSentUnformattable property.
     */
    public long getMqttPublishSentUnformattable() {
        return mqttPublishSentUnformattable;
    }

    /**
     * Sets the value of the mqttPublishSentUnformattable property.
     */
    public void setMqttPublishSentUnformattable(long value) {
        this.mqttPublishSentUnformattable = value;
    }

    /**
     * Gets the value of the mqttPubackRcvd property.
     */
    public long getMqttPubackRcvd() {
        return mqttPubackRcvd;
    }

    /**
     * Sets the value of the mqttPubackRcvd property.
     */
    public void setMqttPubackRcvd(long value) {
        this.mqttPubackRcvd = value;
    }

    /**
     * Gets the value of the mqttPubackSent property.
     */
    public long getMqttPubackSent() {
        return mqttPubackSent;
    }

    /**
     * Sets the value of the mqttPubackSent property.
     */
    public void setMqttPubackSent(long value) {
        this.mqttPubackSent = value;
    }

    /**
     * Gets the value of the mqttPubrecSent property.
     */
    public long getMqttPubrecSent() {
        return mqttPubrecSent;
    }

    /**
     * Sets the value of the mqttPubrecSent property.
     */
    public void setMqttPubrecSent(long value) {
        this.mqttPubrecSent = value;
    }

    /**
     * Gets the value of the mqttPubrelRcvd property.
     */
    public long getMqttPubrelRcvd() {
        return mqttPubrelRcvd;
    }

    /**
     * Sets the value of the mqttPubrelRcvd property.
     */
    public void setMqttPubrelRcvd(long value) {
        this.mqttPubrelRcvd = value;
    }

    /**
     * Gets the value of the mqttPubcompSent property.
     */
    public long getMqttPubcompSent() {
        return mqttPubcompSent;
    }

    /**
     * Sets the value of the mqttPubcompSent property.
     */
    public void setMqttPubcompSent(long value) {
        this.mqttPubcompSent = value;
    }

    /**
     * Gets the value of the mqttSubscribeRcvd property.
     */
    public long getMqttSubscribeRcvd() {
        return mqttSubscribeRcvd;
    }

    /**
     * Sets the value of the mqttSubscribeRcvd property.
     */
    public void setMqttSubscribeRcvd(long value) {
        this.mqttSubscribeRcvd = value;
    }

    /**
     * Gets the value of the mqttSubackSent property.
     */
    public long getMqttSubackSent() {
        return mqttSubackSent;
    }

    /**
     * Sets the value of the mqttSubackSent property.
     */
    public void setMqttSubackSent(long value) {
        this.mqttSubackSent = value;
    }

    /**
     * Gets the value of the mqttSubackSentErr property.
     */
    public long getMqttSubackSentErr() {
        return mqttSubackSentErr;
    }

    /**
     * Sets the value of the mqttSubackSentErr property.
     */
    public void setMqttSubackSentErr(long value) {
        this.mqttSubackSentErr = value;
    }

    /**
     * Gets the value of the mqttUnsubscribeRcvd property.
     */
    public long getMqttUnsubscribeRcvd() {
        return mqttUnsubscribeRcvd;
    }

    /**
     * Sets the value of the mqttUnsubscribeRcvd property.
     */
    public void setMqttUnsubscribeRcvd(long value) {
        this.mqttUnsubscribeRcvd = value;
    }

    /**
     * Gets the value of the mqttUnsubackSent property.
     */
    public long getMqttUnsubackSent() {
        return mqttUnsubackSent;
    }

    /**
     * Sets the value of the mqttUnsubackSent property.
     */
    public void setMqttUnsubackSent(long value) {
        this.mqttUnsubackSent = value;
    }

    /**
     * Gets the value of the mqttPingreqRcvd property.
     */
    public long getMqttPingreqRcvd() {
        return mqttPingreqRcvd;
    }

    /**
     * Sets the value of the mqttPingreqRcvd property.
     */
    public void setMqttPingreqRcvd(long value) {
        this.mqttPingreqRcvd = value;
    }

    /**
     * Gets the value of the mqttPingrespSent property.
     */
    public long getMqttPingrespSent() {
        return mqttPingrespSent;
    }

    /**
     * Sets the value of the mqttPingrespSent property.
     */
    public void setMqttPingrespSent(long value) {
        this.mqttPingrespSent = value;
    }

    /**
     * Gets the value of the mqttDisconnectSent property.
     */
    public long getMqttDisconnectSent() {
        return mqttDisconnectSent;
    }

    /**
     * Sets the value of the mqttDisconnectSent property.
     */
    public void setMqttDisconnectSent(long value) {
        this.mqttDisconnectSent = value;
    }

}
