//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for neighborCountsStatsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="neighborCountsStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="connection" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "neighborCountsStatsType", propOrder = {
        "received",
        "sent",
        "connection"
})
public class NeighborCountsStatsType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger received;
    @XmlElement(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger sent;
    protected List<NeighborCountsStatsType.Connection> connection;

    /**
     * Gets the value of the received property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReceived() {
        return received;
    }

    /**
     * Sets the value of the received property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReceived(BigInteger value) {
        this.received = value;
    }

    /**
     * Gets the value of the sent property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setSent(BigInteger value) {
        this.sent = value;
    }

    /**
     * Gets the value of the connection property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connection property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnection().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeighborCountsStatsType.Connection }
     */
    public List<NeighborCountsStatsType.Connection> getConnection() {
        if (connection == null) {
            connection = new ArrayList<NeighborCountsStatsType.Connection>();
        }
        return this.connection;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Connection {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger received;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger sent;

        /**
         * Gets the value of the name property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the received property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getReceived() {
            return received;
        }

        /**
         * Sets the value of the received property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setReceived(BigInteger value) {
            this.received = value;
        }

        /**
         * Gets the value of the sent property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getSent() {
            return sent;
        }

        /**
         * Sets the value of the sent property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setSent(BigInteger value) {
            this.sent = value;
        }

    }

}
