//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for neighborStatsType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="neighborStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="messages-counts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-messages" type="{}neighborCountsStatsType"/>
 *                   &lt;element name="data-messages" type="{}neighborCountsStatsType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bytes-counts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-bytes" type="{}neighborCountsStatsType"/>
 *                   &lt;element name="data-bytes" type="{}neighborCountsStatsType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="compressed-bytes-counts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="data-bytes" type="{}neighborCountsStatsType"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="current-message-rate-messages-per-second">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="average-message-rate-messages-per-60-seconds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="current-bytes-rate-bytes-per-second">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="average-bytes-rate-bytes-per-60-seconds">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="compression-decompression-stats" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="compressed-bytes-counts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="uncompressed-bytes-counts" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="compression-ratios">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                             &lt;element name="data-bytes" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                       &lt;element name="connection" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                                 &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ssl-stats" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="bytes-counts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="current-bytes-rate-bytes-per-second">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="average-bytes-rate-bytes-per-60-seconds">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                             &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ingress-discards">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="total-ingress-discards" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="no-subscription-match" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="ttl-exceeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="forwarding-loop-supression-router-unexpected-source-router" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="forwarding-loop-supression-unexpected-previous-hop" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="egress-discards">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="total-egress-discards" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                   &lt;element name="data-transmit-congestion" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="data-compression-transmit-congestion" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                   &lt;element name="ttl-exceeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "neighborStatsType", propOrder = {

})
public class NeighborStatsType {

    @XmlElement(name = "messages-counts", required = true)
    protected NeighborStatsType.MessagesCounts messagesCounts;
    @XmlElement(name = "bytes-counts", required = true)
    protected NeighborStatsType.BytesCounts bytesCounts;
    @XmlElement(name = "compressed-bytes-counts")
    protected NeighborStatsType.CompressedBytesCounts compressedBytesCounts;
    @XmlElement(name = "current-message-rate-messages-per-second", required = true)
    protected NeighborStatsType.CurrentMessageRateMessagesPerSecond currentMessageRateMessagesPerSecond;
    @XmlElement(name = "average-message-rate-messages-per-60-seconds", required = true)
    protected NeighborStatsType.AverageMessageRateMessagesPer60Seconds averageMessageRateMessagesPer60Seconds;
    @XmlElement(name = "current-bytes-rate-bytes-per-second", required = true)
    protected NeighborStatsType.CurrentBytesRateBytesPerSecond currentBytesRateBytesPerSecond;
    @XmlElement(name = "average-bytes-rate-bytes-per-60-seconds", required = true)
    protected NeighborStatsType.AverageBytesRateBytesPer60Seconds averageBytesRateBytesPer60Seconds;
    @XmlElement(name = "compression-decompression-stats")
    protected NeighborStatsType.CompressionDecompressionStats compressionDecompressionStats;
    @XmlElement(name = "ssl-stats")
    protected NeighborStatsType.SslStats sslStats;
    @XmlElement(name = "ingress-discards", required = true)
    protected NeighborStatsType.IngressDiscards ingressDiscards;
    @XmlElement(name = "egress-discards", required = true)
    protected NeighborStatsType.EgressDiscards egressDiscards;

    /**
     * Gets the value of the messagesCounts property.
     *
     * @return possible object is
     * {@link NeighborStatsType.MessagesCounts }
     */
    public NeighborStatsType.MessagesCounts getMessagesCounts() {
        return messagesCounts;
    }

    /**
     * Sets the value of the messagesCounts property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.MessagesCounts }
     */
    public void setMessagesCounts(NeighborStatsType.MessagesCounts value) {
        this.messagesCounts = value;
    }

    /**
     * Gets the value of the bytesCounts property.
     *
     * @return possible object is
     * {@link NeighborStatsType.BytesCounts }
     */
    public NeighborStatsType.BytesCounts getBytesCounts() {
        return bytesCounts;
    }

    /**
     * Sets the value of the bytesCounts property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.BytesCounts }
     */
    public void setBytesCounts(NeighborStatsType.BytesCounts value) {
        this.bytesCounts = value;
    }

    /**
     * Gets the value of the compressedBytesCounts property.
     *
     * @return possible object is
     * {@link NeighborStatsType.CompressedBytesCounts }
     */
    public NeighborStatsType.CompressedBytesCounts getCompressedBytesCounts() {
        return compressedBytesCounts;
    }

    /**
     * Sets the value of the compressedBytesCounts property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.CompressedBytesCounts }
     */
    public void setCompressedBytesCounts(NeighborStatsType.CompressedBytesCounts value) {
        this.compressedBytesCounts = value;
    }

    /**
     * Gets the value of the currentMessageRateMessagesPerSecond property.
     *
     * @return possible object is
     * {@link NeighborStatsType.CurrentMessageRateMessagesPerSecond }
     */
    public NeighborStatsType.CurrentMessageRateMessagesPerSecond getCurrentMessageRateMessagesPerSecond() {
        return currentMessageRateMessagesPerSecond;
    }

    /**
     * Sets the value of the currentMessageRateMessagesPerSecond property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.CurrentMessageRateMessagesPerSecond }
     */
    public void setCurrentMessageRateMessagesPerSecond(NeighborStatsType.CurrentMessageRateMessagesPerSecond value) {
        this.currentMessageRateMessagesPerSecond = value;
    }

    /**
     * Gets the value of the averageMessageRateMessagesPer60Seconds property.
     *
     * @return possible object is
     * {@link NeighborStatsType.AverageMessageRateMessagesPer60Seconds }
     */
    public NeighborStatsType.AverageMessageRateMessagesPer60Seconds getAverageMessageRateMessagesPer60Seconds() {
        return averageMessageRateMessagesPer60Seconds;
    }

    /**
     * Sets the value of the averageMessageRateMessagesPer60Seconds property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.AverageMessageRateMessagesPer60Seconds }
     */
    public void setAverageMessageRateMessagesPer60Seconds(NeighborStatsType.AverageMessageRateMessagesPer60Seconds value) {
        this.averageMessageRateMessagesPer60Seconds = value;
    }

    /**
     * Gets the value of the currentBytesRateBytesPerSecond property.
     *
     * @return possible object is
     * {@link NeighborStatsType.CurrentBytesRateBytesPerSecond }
     */
    public NeighborStatsType.CurrentBytesRateBytesPerSecond getCurrentBytesRateBytesPerSecond() {
        return currentBytesRateBytesPerSecond;
    }

    /**
     * Sets the value of the currentBytesRateBytesPerSecond property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.CurrentBytesRateBytesPerSecond }
     */
    public void setCurrentBytesRateBytesPerSecond(NeighborStatsType.CurrentBytesRateBytesPerSecond value) {
        this.currentBytesRateBytesPerSecond = value;
    }

    /**
     * Gets the value of the averageBytesRateBytesPer60Seconds property.
     *
     * @return possible object is
     * {@link NeighborStatsType.AverageBytesRateBytesPer60Seconds }
     */
    public NeighborStatsType.AverageBytesRateBytesPer60Seconds getAverageBytesRateBytesPer60Seconds() {
        return averageBytesRateBytesPer60Seconds;
    }

    /**
     * Sets the value of the averageBytesRateBytesPer60Seconds property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.AverageBytesRateBytesPer60Seconds }
     */
    public void setAverageBytesRateBytesPer60Seconds(NeighborStatsType.AverageBytesRateBytesPer60Seconds value) {
        this.averageBytesRateBytesPer60Seconds = value;
    }

    /**
     * Gets the value of the compressionDecompressionStats property.
     *
     * @return possible object is
     * {@link NeighborStatsType.CompressionDecompressionStats }
     */
    public NeighborStatsType.CompressionDecompressionStats getCompressionDecompressionStats() {
        return compressionDecompressionStats;
    }

    /**
     * Sets the value of the compressionDecompressionStats property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.CompressionDecompressionStats }
     */
    public void setCompressionDecompressionStats(NeighborStatsType.CompressionDecompressionStats value) {
        this.compressionDecompressionStats = value;
    }

    /**
     * Gets the value of the sslStats property.
     *
     * @return possible object is
     * {@link NeighborStatsType.SslStats }
     */
    public NeighborStatsType.SslStats getSslStats() {
        return sslStats;
    }

    /**
     * Sets the value of the sslStats property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.SslStats }
     */
    public void setSslStats(NeighborStatsType.SslStats value) {
        this.sslStats = value;
    }

    /**
     * Gets the value of the ingressDiscards property.
     *
     * @return possible object is
     * {@link NeighborStatsType.IngressDiscards }
     */
    public NeighborStatsType.IngressDiscards getIngressDiscards() {
        return ingressDiscards;
    }

    /**
     * Sets the value of the ingressDiscards property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.IngressDiscards }
     */
    public void setIngressDiscards(NeighborStatsType.IngressDiscards value) {
        this.ingressDiscards = value;
    }

    /**
     * Gets the value of the egressDiscards property.
     *
     * @return possible object is
     * {@link NeighborStatsType.EgressDiscards }
     */
    public NeighborStatsType.EgressDiscards getEgressDiscards() {
        return egressDiscards;
    }

    /**
     * Sets the value of the egressDiscards property.
     *
     * @param value allowed object is
     *              {@link NeighborStatsType.EgressDiscards }
     */
    public void setEgressDiscards(NeighborStatsType.EgressDiscards value) {
        this.egressDiscards = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ingress",
            "egress",
            "controlRate",
            "dataRate"
    })
    public static class AverageBytesRateBytesPer60Seconds {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ingress;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger egress;
        @XmlElement(name = "control-rate")
        protected NeighborRatesStatsType controlRate;
        @XmlElement(name = "data-rate")
        protected NeighborRatesStatsType dataRate;

        /**
         * Gets the value of the ingress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getIngress() {
            return ingress;
        }

        /**
         * Sets the value of the ingress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setIngress(BigInteger value) {
            this.ingress = value;
        }

        /**
         * Gets the value of the egress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getEgress() {
            return egress;
        }

        /**
         * Sets the value of the egress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setEgress(BigInteger value) {
            this.egress = value;
        }

        /**
         * Gets the value of the controlRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getControlRate() {
            return controlRate;
        }

        /**
         * Sets the value of the controlRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setControlRate(NeighborRatesStatsType value) {
            this.controlRate = value;
        }

        /**
         * Gets the value of the dataRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getDataRate() {
            return dataRate;
        }

        /**
         * Sets the value of the dataRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setDataRate(NeighborRatesStatsType value) {
            this.dataRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class AverageMessageRateMessagesPer60Seconds {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ingress;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger egress;
        @XmlElement(name = "control-rate")
        protected NeighborRatesStatsType controlRate;
        @XmlElement(name = "data-rate")
        protected NeighborRatesStatsType dataRate;

        /**
         * Gets the value of the ingress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getIngress() {
            return ingress;
        }

        /**
         * Sets the value of the ingress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setIngress(BigInteger value) {
            this.ingress = value;
        }

        /**
         * Gets the value of the egress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getEgress() {
            return egress;
        }

        /**
         * Sets the value of the egress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setEgress(BigInteger value) {
            this.egress = value;
        }

        /**
         * Gets the value of the controlRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getControlRate() {
            return controlRate;
        }

        /**
         * Sets the value of the controlRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setControlRate(NeighborRatesStatsType value) {
            this.controlRate = value;
        }

        /**
         * Gets the value of the dataRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getDataRate() {
            return dataRate;
        }

        /**
         * Sets the value of the dataRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setDataRate(NeighborRatesStatsType value) {
            this.dataRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-bytes" type="{}neighborCountsStatsType"/>
     *         &lt;element name="data-bytes" type="{}neighborCountsStatsType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class BytesCounts {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger received;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger sent;
        @XmlElement(name = "control-bytes", required = true)
        protected NeighborCountsStatsType controlBytes;
        @XmlElement(name = "data-bytes", required = true)
        protected NeighborCountsStatsType dataBytes;

        /**
         * Gets the value of the received property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getReceived() {
            return received;
        }

        /**
         * Sets the value of the received property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setReceived(BigInteger value) {
            this.received = value;
        }

        /**
         * Gets the value of the sent property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getSent() {
            return sent;
        }

        /**
         * Sets the value of the sent property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setSent(BigInteger value) {
            this.sent = value;
        }

        /**
         * Gets the value of the controlBytes property.
         *
         * @return possible object is
         * {@link NeighborCountsStatsType }
         */
        public NeighborCountsStatsType getControlBytes() {
            return controlBytes;
        }

        /**
         * Sets the value of the controlBytes property.
         *
         * @param value allowed object is
         *              {@link NeighborCountsStatsType }
         */
        public void setControlBytes(NeighborCountsStatsType value) {
            this.controlBytes = value;
        }

        /**
         * Gets the value of the dataBytes property.
         *
         * @return possible object is
         * {@link NeighborCountsStatsType }
         */
        public NeighborCountsStatsType getDataBytes() {
            return dataBytes;
        }

        /**
         * Sets the value of the dataBytes property.
         *
         * @param value allowed object is
         *              {@link NeighborCountsStatsType }
         */
        public void setDataBytes(NeighborCountsStatsType value) {
            this.dataBytes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="data-bytes" type="{}neighborCountsStatsType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CompressedBytesCounts {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger received;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger sent;
        @XmlElement(name = "data-bytes", required = true)
        protected NeighborCountsStatsType dataBytes;

        /**
         * Gets the value of the received property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getReceived() {
            return received;
        }

        /**
         * Sets the value of the received property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setReceived(BigInteger value) {
            this.received = value;
        }

        /**
         * Gets the value of the sent property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getSent() {
            return sent;
        }

        /**
         * Sets the value of the sent property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setSent(BigInteger value) {
            this.sent = value;
        }

        /**
         * Gets the value of the dataBytes property.
         *
         * @return possible object is
         * {@link NeighborCountsStatsType }
         */
        public NeighborCountsStatsType getDataBytes() {
            return dataBytes;
        }

        /**
         * Sets the value of the dataBytes property.
         *
         * @param value allowed object is
         *              {@link NeighborCountsStatsType }
         */
        public void setDataBytes(NeighborCountsStatsType value) {
            this.dataBytes = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="compressed-bytes-counts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="uncompressed-bytes-counts" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="compression-ratios">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                   &lt;element name="data-bytes" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                             &lt;element name="connection" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                                       &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CompressionDecompressionStats {

        @XmlElement(name = "compressed-bytes-counts", required = true)
        protected NeighborStatsType.CompressionDecompressionStats.CompressedBytesCounts compressedBytesCounts;
        @XmlElement(name = "uncompressed-bytes-counts")
        protected NeighborStatsType.CompressionDecompressionStats.UncompressedBytesCounts uncompressedBytesCounts;
        @XmlElement(name = "compression-ratios", required = true)
        protected NeighborStatsType.CompressionDecompressionStats.CompressionRatios compressionRatios;

        /**
         * Gets the value of the compressedBytesCounts property.
         *
         * @return possible object is
         * {@link NeighborStatsType.CompressionDecompressionStats.CompressedBytesCounts }
         */
        public NeighborStatsType.CompressionDecompressionStats.CompressedBytesCounts getCompressedBytesCounts() {
            return compressedBytesCounts;
        }

        /**
         * Sets the value of the compressedBytesCounts property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.CompressionDecompressionStats.CompressedBytesCounts }
         */
        public void setCompressedBytesCounts(NeighborStatsType.CompressionDecompressionStats.CompressedBytesCounts value) {
            this.compressedBytesCounts = value;
        }

        /**
         * Gets the value of the uncompressedBytesCounts property.
         *
         * @return possible object is
         * {@link NeighborStatsType.CompressionDecompressionStats.UncompressedBytesCounts }
         */
        public NeighborStatsType.CompressionDecompressionStats.UncompressedBytesCounts getUncompressedBytesCounts() {
            return uncompressedBytesCounts;
        }

        /**
         * Sets the value of the uncompressedBytesCounts property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.CompressionDecompressionStats.UncompressedBytesCounts }
         */
        public void setUncompressedBytesCounts(NeighborStatsType.CompressionDecompressionStats.UncompressedBytesCounts value) {
            this.uncompressedBytesCounts = value;
        }

        /**
         * Gets the value of the compressionRatios property.
         *
         * @return possible object is
         * {@link NeighborStatsType.CompressionDecompressionStats.CompressionRatios }
         */
        public NeighborStatsType.CompressionDecompressionStats.CompressionRatios getCompressionRatios() {
            return compressionRatios;
        }

        /**
         * Sets the value of the compressionRatios property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.CompressionDecompressionStats.CompressionRatios }
         */
        public void setCompressionRatios(NeighborStatsType.CompressionDecompressionStats.CompressionRatios value) {
            this.compressionRatios = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class CompressedBytesCounts {

            @XmlElement(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger received;
            @XmlElement(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger sent;
            @XmlElement(name = "data-bytes")
            protected NeighborCountsStatsType dataBytes;

            /**
             * Gets the value of the received property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getReceived() {
                return received;
            }

            /**
             * Sets the value of the received property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setReceived(BigInteger value) {
                this.received = value;
            }

            /**
             * Gets the value of the sent property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSent() {
                return sent;
            }

            /**
             * Sets the value of the sent property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSent(BigInteger value) {
                this.sent = value;
            }

            /**
             * Gets the value of the dataBytes property.
             *
             * @return possible object is
             * {@link NeighborCountsStatsType }
             */
            public NeighborCountsStatsType getDataBytes() {
                return dataBytes;
            }

            /**
             * Sets the value of the dataBytes property.
             *
             * @param value allowed object is
             *              {@link NeighborCountsStatsType }
             */
            public void setDataBytes(NeighborCountsStatsType value) {
                this.dataBytes = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *         &lt;element name="data-bytes" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                   &lt;element name="connection" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                             &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class CompressionRatios {

            protected double received;
            protected double sent;
            @XmlElement(name = "data-bytes")
            protected NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes dataBytes;

            /**
             * Gets the value of the received property.
             */
            public double getReceived() {
                return received;
            }

            /**
             * Sets the value of the received property.
             */
            public void setReceived(double value) {
                this.received = value;
            }

            /**
             * Gets the value of the sent property.
             */
            public double getSent() {
                return sent;
            }

            /**
             * Sets the value of the sent property.
             */
            public void setSent(double value) {
                this.sent = value;
            }

            /**
             * Gets the value of the dataBytes property.
             *
             * @return possible object is
             * {@link NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes }
             */
            public NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes getDataBytes() {
                return dataBytes;
            }

            /**
             * Sets the value of the dataBytes property.
             *
             * @param value allowed object is
             *              {@link NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes }
             */
            public void setDataBytes(NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes value) {
                this.dataBytes = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *         &lt;element name="connection" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "received",
                    "sent",
                    "connection"
            })
            public static class DataBytes {

                protected double received;
                protected double sent;
                protected List<NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes.Connection> connection;

                /**
                 * Gets the value of the received property.
                 */
                public double getReceived() {
                    return received;
                }

                /**
                 * Sets the value of the received property.
                 */
                public void setReceived(double value) {
                    this.received = value;
                }

                /**
                 * Gets the value of the sent property.
                 */
                public double getSent() {
                    return sent;
                }

                /**
                 * Sets the value of the sent property.
                 */
                public void setSent(double value) {
                    this.sent = value;
                }

                /**
                 * Gets the value of the connection property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the connection property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getConnection().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes.Connection }
                 */
                public List<NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes.Connection> getConnection() {
                    if (connection == null) {
                        connection = new ArrayList<NeighborStatsType.CompressionDecompressionStats.CompressionRatios.DataBytes.Connection>();
                    }
                    return this.connection;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}double"/>
                 *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}double"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                        "name",
                        "received",
                        "sent"
                })
                public static class Connection {

                    @XmlElement(required = true)
                    protected String name;
                    protected double received;
                    protected double sent;

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     * {@link String }
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *              {@link String }
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the received property.
                     */
                    public double getReceived() {
                        return received;
                    }

                    /**
                     * Sets the value of the received property.
                     */
                    public void setReceived(double value) {
                        this.received = value;
                    }

                    /**
                     * Gets the value of the sent property.
                     */
                    public double getSent() {
                        return sent;
                    }

                    /**
                     * Sets the value of the sent property.
                     */
                    public void setSent(double value) {
                        this.sent = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class UncompressedBytesCounts {

            @XmlElement(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger received;
            @XmlElement(required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger sent;

            /**
             * Gets the value of the received property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getReceived() {
                return received;
            }

            /**
             * Sets the value of the received property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setReceived(BigInteger value) {
                this.received = value;
            }

            /**
             * Gets the value of the sent property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSent() {
                return sent;
            }

            /**
             * Sets the value of the sent property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSent(BigInteger value) {
                this.sent = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CurrentBytesRateBytesPerSecond {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ingress;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger egress;
        @XmlElement(name = "control-rate")
        protected NeighborRatesStatsType controlRate;
        @XmlElement(name = "data-rate")
        protected NeighborRatesStatsType dataRate;

        /**
         * Gets the value of the ingress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getIngress() {
            return ingress;
        }

        /**
         * Sets the value of the ingress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setIngress(BigInteger value) {
            this.ingress = value;
        }

        /**
         * Gets the value of the egress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getEgress() {
            return egress;
        }

        /**
         * Sets the value of the egress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setEgress(BigInteger value) {
            this.egress = value;
        }

        /**
         * Gets the value of the controlRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getControlRate() {
            return controlRate;
        }

        /**
         * Sets the value of the controlRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setControlRate(NeighborRatesStatsType value) {
            this.controlRate = value;
        }

        /**
         * Gets the value of the dataRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getDataRate() {
            return dataRate;
        }

        /**
         * Sets the value of the dataRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setDataRate(NeighborRatesStatsType value) {
            this.dataRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CurrentMessageRateMessagesPerSecond {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ingress;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger egress;
        @XmlElement(name = "control-rate")
        protected NeighborRatesStatsType controlRate;
        @XmlElement(name = "data-rate")
        protected NeighborRatesStatsType dataRate;

        /**
         * Gets the value of the ingress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getIngress() {
            return ingress;
        }

        /**
         * Sets the value of the ingress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setIngress(BigInteger value) {
            this.ingress = value;
        }

        /**
         * Gets the value of the egress property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getEgress() {
            return egress;
        }

        /**
         * Sets the value of the egress property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setEgress(BigInteger value) {
            this.egress = value;
        }

        /**
         * Gets the value of the controlRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getControlRate() {
            return controlRate;
        }

        /**
         * Sets the value of the controlRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setControlRate(NeighborRatesStatsType value) {
            this.controlRate = value;
        }

        /**
         * Gets the value of the dataRate property.
         *
         * @return possible object is
         * {@link NeighborRatesStatsType }
         */
        public NeighborRatesStatsType getDataRate() {
            return dataRate;
        }

        /**
         * Sets the value of the dataRate property.
         *
         * @param value allowed object is
         *              {@link NeighborRatesStatsType }
         */
        public void setDataRate(NeighborRatesStatsType value) {
            this.dataRate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="total-egress-discards" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="data-transmit-congestion" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="data-compression-transmit-congestion" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="ttl-exceeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class EgressDiscards {

        @XmlElement(name = "total-egress-discards", required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger totalEgressDiscards;
        @XmlElement(name = "data-transmit-congestion")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger dataTransmitCongestion;
        @XmlElement(name = "data-compression-transmit-congestion")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger dataCompressionTransmitCongestion;
        @XmlElement(name = "ttl-exceeded")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ttlExceeded;

        /**
         * Gets the value of the totalEgressDiscards property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getTotalEgressDiscards() {
            return totalEgressDiscards;
        }

        /**
         * Sets the value of the totalEgressDiscards property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setTotalEgressDiscards(BigInteger value) {
            this.totalEgressDiscards = value;
        }

        /**
         * Gets the value of the dataTransmitCongestion property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getDataTransmitCongestion() {
            return dataTransmitCongestion;
        }

        /**
         * Sets the value of the dataTransmitCongestion property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setDataTransmitCongestion(BigInteger value) {
            this.dataTransmitCongestion = value;
        }

        /**
         * Gets the value of the dataCompressionTransmitCongestion property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getDataCompressionTransmitCongestion() {
            return dataCompressionTransmitCongestion;
        }

        /**
         * Sets the value of the dataCompressionTransmitCongestion property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setDataCompressionTransmitCongestion(BigInteger value) {
            this.dataCompressionTransmitCongestion = value;
        }

        /**
         * Gets the value of the ttlExceeded property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getTtlExceeded() {
            return ttlExceeded;
        }

        /**
         * Sets the value of the ttlExceeded property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setTtlExceeded(BigInteger value) {
            this.ttlExceeded = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="total-ingress-discards" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="no-subscription-match" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="ttl-exceeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="forwarding-loop-supression-router-unexpected-source-router" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *         &lt;element name="forwarding-loop-supression-unexpected-previous-hop" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class IngressDiscards {

        @XmlElement(name = "total-ingress-discards", required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger totalIngressDiscards;
        @XmlElement(name = "no-subscription-match")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger noSubscriptionMatch;
        @XmlElement(name = "ttl-exceeded")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger ttlExceeded;
        @XmlElement(name = "forwarding-loop-supression-router-unexpected-source-router")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger forwardingLoopSupressionRouterUnexpectedSourceRouter;
        @XmlElement(name = "forwarding-loop-supression-unexpected-previous-hop")
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger forwardingLoopSupressionUnexpectedPreviousHop;

        /**
         * Gets the value of the totalIngressDiscards property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getTotalIngressDiscards() {
            return totalIngressDiscards;
        }

        /**
         * Sets the value of the totalIngressDiscards property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setTotalIngressDiscards(BigInteger value) {
            this.totalIngressDiscards = value;
        }

        /**
         * Gets the value of the noSubscriptionMatch property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getNoSubscriptionMatch() {
            return noSubscriptionMatch;
        }

        /**
         * Sets the value of the noSubscriptionMatch property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setNoSubscriptionMatch(BigInteger value) {
            this.noSubscriptionMatch = value;
        }

        /**
         * Gets the value of the ttlExceeded property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getTtlExceeded() {
            return ttlExceeded;
        }

        /**
         * Sets the value of the ttlExceeded property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setTtlExceeded(BigInteger value) {
            this.ttlExceeded = value;
        }

        /**
         * Gets the value of the forwardingLoopSupressionRouterUnexpectedSourceRouter property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getForwardingLoopSupressionRouterUnexpectedSourceRouter() {
            return forwardingLoopSupressionRouterUnexpectedSourceRouter;
        }

        /**
         * Sets the value of the forwardingLoopSupressionRouterUnexpectedSourceRouter property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setForwardingLoopSupressionRouterUnexpectedSourceRouter(BigInteger value) {
            this.forwardingLoopSupressionRouterUnexpectedSourceRouter = value;
        }

        /**
         * Gets the value of the forwardingLoopSupressionUnexpectedPreviousHop property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getForwardingLoopSupressionUnexpectedPreviousHop() {
            return forwardingLoopSupressionUnexpectedPreviousHop;
        }

        /**
         * Sets the value of the forwardingLoopSupressionUnexpectedPreviousHop property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setForwardingLoopSupressionUnexpectedPreviousHop(BigInteger value) {
            this.forwardingLoopSupressionUnexpectedPreviousHop = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *         &lt;element name="control-messages" type="{}neighborCountsStatsType"/>
     *         &lt;element name="data-messages" type="{}neighborCountsStatsType"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class MessagesCounts {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger received;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger sent;
        @XmlElement(name = "control-messages", required = true)
        protected NeighborCountsStatsType controlMessages;
        @XmlElement(name = "data-messages", required = true)
        protected NeighborCountsStatsType dataMessages;

        /**
         * Gets the value of the received property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getReceived() {
            return received;
        }

        /**
         * Sets the value of the received property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setReceived(BigInteger value) {
            this.received = value;
        }

        /**
         * Gets the value of the sent property.
         *
         * @return possible object is
         * {@link BigInteger }
         */
        public BigInteger getSent() {
            return sent;
        }

        /**
         * Sets the value of the sent property.
         *
         * @param value allowed object is
         *              {@link BigInteger }
         */
        public void setSent(BigInteger value) {
            this.sent = value;
        }

        /**
         * Gets the value of the controlMessages property.
         *
         * @return possible object is
         * {@link NeighborCountsStatsType }
         */
        public NeighborCountsStatsType getControlMessages() {
            return controlMessages;
        }

        /**
         * Sets the value of the controlMessages property.
         *
         * @param value allowed object is
         *              {@link NeighborCountsStatsType }
         */
        public void setControlMessages(NeighborCountsStatsType value) {
            this.controlMessages = value;
        }

        /**
         * Gets the value of the dataMessages property.
         *
         * @return possible object is
         * {@link NeighborCountsStatsType }
         */
        public NeighborCountsStatsType getDataMessages() {
            return dataMessages;
        }

        /**
         * Sets the value of the dataMessages property.
         *
         * @param value allowed object is
         *              {@link NeighborCountsStatsType }
         */
        public void setDataMessages(NeighborCountsStatsType value) {
            this.dataMessages = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="bytes-counts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="current-bytes-rate-bytes-per-second">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="average-bytes-rate-bytes-per-60-seconds">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SslStats {

        @XmlElement(name = "bytes-counts", required = true)
        protected NeighborStatsType.SslStats.BytesCounts bytesCounts;
        @XmlElement(name = "current-bytes-rate-bytes-per-second", required = true)
        protected NeighborStatsType.SslStats.CurrentBytesRateBytesPerSecond currentBytesRateBytesPerSecond;
        @XmlElement(name = "average-bytes-rate-bytes-per-60-seconds", required = true)
        protected NeighborStatsType.SslStats.AverageBytesRateBytesPer60Seconds averageBytesRateBytesPer60Seconds;

        /**
         * Gets the value of the bytesCounts property.
         *
         * @return possible object is
         * {@link NeighborStatsType.SslStats.BytesCounts }
         */
        public NeighborStatsType.SslStats.BytesCounts getBytesCounts() {
            return bytesCounts;
        }

        /**
         * Sets the value of the bytesCounts property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.SslStats.BytesCounts }
         */
        public void setBytesCounts(NeighborStatsType.SslStats.BytesCounts value) {
            this.bytesCounts = value;
        }

        /**
         * Gets the value of the currentBytesRateBytesPerSecond property.
         *
         * @return possible object is
         * {@link NeighborStatsType.SslStats.CurrentBytesRateBytesPerSecond }
         */
        public NeighborStatsType.SslStats.CurrentBytesRateBytesPerSecond getCurrentBytesRateBytesPerSecond() {
            return currentBytesRateBytesPerSecond;
        }

        /**
         * Sets the value of the currentBytesRateBytesPerSecond property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.SslStats.CurrentBytesRateBytesPerSecond }
         */
        public void setCurrentBytesRateBytesPerSecond(NeighborStatsType.SslStats.CurrentBytesRateBytesPerSecond value) {
            this.currentBytesRateBytesPerSecond = value;
        }

        /**
         * Gets the value of the averageBytesRateBytesPer60Seconds property.
         *
         * @return possible object is
         * {@link NeighborStatsType.SslStats.AverageBytesRateBytesPer60Seconds }
         */
        public NeighborStatsType.SslStats.AverageBytesRateBytesPer60Seconds getAverageBytesRateBytesPer60Seconds() {
            return averageBytesRateBytesPer60Seconds;
        }

        /**
         * Sets the value of the averageBytesRateBytesPer60Seconds property.
         *
         * @param value allowed object is
         *              {@link NeighborStatsType.SslStats.AverageBytesRateBytesPer60Seconds }
         */
        public void setAverageBytesRateBytesPer60Seconds(NeighborStatsType.SslStats.AverageBytesRateBytesPer60Seconds value) {
            this.averageBytesRateBytesPer60Seconds = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "ingress",
                "egress",
                "dataRate"
        })
        public static class AverageBytesRateBytesPer60Seconds {

            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger ingress;
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger egress;
            @XmlElement(name = "data-rate")
            protected NeighborRatesStatsType dataRate;

            /**
             * Gets the value of the ingress property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getIngress() {
                return ingress;
            }

            /**
             * Sets the value of the ingress property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setIngress(BigInteger value) {
                this.ingress = value;
            }

            /**
             * Gets the value of the egress property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getEgress() {
                return egress;
            }

            /**
             * Sets the value of the egress property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setEgress(BigInteger value) {
                this.egress = value;
            }

            /**
             * Gets the value of the dataRate property.
             *
             * @return possible object is
             * {@link NeighborRatesStatsType }
             */
            public NeighborRatesStatsType getDataRate() {
                return dataRate;
            }

            /**
             * Sets the value of the dataRate property.
             *
             * @param value allowed object is
             *              {@link NeighborRatesStatsType }
             */
            public void setDataRate(NeighborRatesStatsType value) {
                this.dataRate = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="received" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="data-bytes" type="{}neighborCountsStatsType" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class BytesCounts {

            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger received;
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger sent;
            @XmlElement(name = "data-bytes")
            protected NeighborCountsStatsType dataBytes;

            /**
             * Gets the value of the received property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getReceived() {
                return received;
            }

            /**
             * Sets the value of the received property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setReceived(BigInteger value) {
                this.received = value;
            }

            /**
             * Gets the value of the sent property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSent() {
                return sent;
            }

            /**
             * Sets the value of the sent property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSent(BigInteger value) {
                this.sent = value;
            }

            /**
             * Gets the value of the dataBytes property.
             *
             * @return possible object is
             * {@link NeighborCountsStatsType }
             */
            public NeighborCountsStatsType getDataBytes() {
                return dataBytes;
            }

            /**
             * Sets the value of the dataBytes property.
             *
             * @param value allowed object is
             *              {@link NeighborCountsStatsType }
             */
            public void setDataBytes(NeighborCountsStatsType value) {
                this.dataBytes = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="ingress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="egress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *         &lt;element name="data-rate" type="{}neighborRatesStatsType" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class CurrentBytesRateBytesPerSecond {

            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger ingress;
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger egress;
            @XmlElement(name = "data-rate")
            protected NeighborRatesStatsType dataRate;

            /**
             * Gets the value of the ingress property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getIngress() {
                return ingress;
            }

            /**
             * Sets the value of the ingress property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setIngress(BigInteger value) {
                this.ingress = value;
            }

            /**
             * Gets the value of the egress property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getEgress() {
                return egress;
            }

            /**
             * Sets the value of the egress property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setEgress(BigInteger value) {
                this.egress = value;
            }

            /**
             * Gets the value of the dataRate property.
             *
             * @return possible object is
             * {@link NeighborRatesStatsType }
             */
            public NeighborRatesStatsType getDataRate() {
                return dataRate;
            }

            /**
             * Sets the value of the dataRate property.
             *
             * @param value allowed object is
             *              {@link NeighborRatesStatsType }
             */
            public void setDataRate(NeighborRatesStatsType value) {
                this.dataRate = value;
            }

        }

    }

}
