//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qendpt-info-type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="qendpt-info-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="message-vpn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="durable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="endpt-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ingress-config-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="egress-config-status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="access-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ingress-selector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ingress-selector-present" type="{}yes-no-type" minOccurs="0"/>
 *         &lt;element name="egress-selector-present" type="{}yes-no-type" minOccurs="0"/>
 *         &lt;element name="owner" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="created-by-mgmt" type="{}yes-no-type" minOccurs="0"/>
 *         &lt;element name="others-permission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="quota" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="respect-message-priority" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="respect-ttl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-ttl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dead-message-queue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reject-msg-to-sender-on-discard" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reject-msg-to-sender-on-discard-including-when-shutdown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bind-time-forwarding-mode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="num-messages-spooled" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="current-spool-usage-in-mb" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="high-water-mark-in-mb" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="total-delivered-unacked-msgs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="max-delivered-unacked-msgs-per-flow" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="total-acked-msgs-in-progress" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="max-redelivery" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="consumer-ack-propagation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reject-low-priority-msg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reject-low-priority-msg-limit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="low-priority-msg-congestion-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max-message-size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="oldest-msg-id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="newest-msg-id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="bind-count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="bind-count-threshold-high" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="bind-count-threshold-high-clear" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="bind-count-threshold-high-percentage" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="bind-count-threshold-high-clear-percentage" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="max-bind-count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="operational-max-bind-count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="topic-subscription-count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="network-topic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clients" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="client" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="is-active" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status-updates" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="deliver-from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="flow-state-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="no-local-delivery" type="{}yes-no-type" minOccurs="0"/>
 *                             &lt;element name="request-redelivery" type="{}yes-no-type" minOccurs="0"/>
 *                             &lt;element name="egress-selector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="window-size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="connect-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="activation-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="flow-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *                             &lt;element name="last-msg-id-delivered" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="event" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="event-thresholds" type="{}event-thresholds" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qendpt-info-type", propOrder = {

})
public class QendptInfoType {

    @XmlElement(name = "message-vpn")
    protected String messageVpn;
    protected Boolean durable;
    @XmlElement(name = "endpt-id")
    @XmlSchemaType(name = "unsignedInt")
    protected Long endptId;
    protected String type;
    @XmlElement(name = "ingress-config-status")
    protected String ingressConfigStatus;
    @XmlElement(name = "egress-config-status")
    protected String egressConfigStatus;
    @XmlElement(name = "access-type")
    protected String accessType;
    @XmlElement(name = "ingress-selector")
    protected String ingressSelector;
    @XmlElement(name = "ingress-selector-present")
    protected String ingressSelectorPresent;
    @XmlElement(name = "egress-selector-present")
    protected String egressSelectorPresent;
    protected String owner;
    @XmlElement(name = "created-by-mgmt")
    protected String createdByMgmt;
    @XmlElement(name = "others-permission")
    protected String othersPermission;
    protected String destination;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger quota;
    @XmlElement(name = "respect-message-priority")
    protected String respectMessagePriority;
    @XmlElement(name = "respect-ttl")
    protected String respectTtl;
    @XmlElement(name = "max-ttl")
    protected String maxTtl;
    @XmlElement(name = "dead-message-queue")
    protected String deadMessageQueue;
    @XmlElement(name = "reject-msg-to-sender-on-discard")
    protected String rejectMsgToSenderOnDiscard;
    @XmlElement(name = "reject-msg-to-sender-on-discard-including-when-shutdown")
    protected String rejectMsgToSenderOnDiscardIncludingWhenShutdown;
    @XmlElement(name = "bind-time-forwarding-mode")
    protected String bindTimeForwardingMode;
    @XmlElement(name = "num-messages-spooled")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger numMessagesSpooled;
    @XmlElement(name = "current-spool-usage-in-mb")
    protected Double currentSpoolUsageInMb;
    @XmlElement(name = "high-water-mark-in-mb")
    protected Double highWaterMarkInMb;
    @XmlElement(name = "total-delivered-unacked-msgs")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalDeliveredUnackedMsgs;
    @XmlElement(name = "max-delivered-unacked-msgs-per-flow")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxDeliveredUnackedMsgsPerFlow;
    @XmlElement(name = "total-acked-msgs-in-progress")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalAckedMsgsInProgress;
    @XmlElement(name = "max-redelivery")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxRedelivery;
    @XmlElement(name = "consumer-ack-propagation")
    protected String consumerAckPropagation;
    @XmlElement(name = "reject-low-priority-msg")
    protected String rejectLowPriorityMsg;
    @XmlElement(name = "reject-low-priority-msg-limit")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger rejectLowPriorityMsgLimit;
    @XmlElement(name = "low-priority-msg-congestion-state")
    protected String lowPriorityMsgCongestionState;
    @XmlElement(name = "max-message-size")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger maxMessageSize;
    @XmlElement(name = "oldest-msg-id")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger oldestMsgId;
    @XmlElement(name = "newest-msg-id")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger newestMsgId;
    @XmlElement(name = "bind-count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bindCount;
    @XmlElement(name = "bind-count-threshold-high")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bindCountThresholdHigh;
    @XmlElement(name = "bind-count-threshold-high-clear")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bindCountThresholdHighClear;
    @XmlElement(name = "bind-count-threshold-high-percentage")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bindCountThresholdHighPercentage;
    @XmlElement(name = "bind-count-threshold-high-clear-percentage")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bindCountThresholdHighClearPercentage;
    @XmlElement(name = "max-bind-count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maxBindCount;
    @XmlElement(name = "operational-max-bind-count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long operationalMaxBindCount;
    @XmlElement(name = "topic-subscription-count")
    @XmlSchemaType(name = "unsignedInt")
    protected Long topicSubscriptionCount;
    @XmlElement(name = "network-topic")
    protected String networkTopic;
    protected QendptInfoType.Clients clients;
    protected QendptInfoType.Event event;

    /**
     * Gets the value of the messageVpn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMessageVpn() {
        return messageVpn;
    }

    /**
     * Sets the value of the messageVpn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMessageVpn(String value) {
        this.messageVpn = value;
    }

    /**
     * Gets the value of the durable property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isDurable() {
        return durable;
    }

    /**
     * Sets the value of the durable property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDurable(Boolean value) {
        this.durable = value;
    }

    /**
     * Gets the value of the endptId property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getEndptId() {
        return endptId;
    }

    /**
     * Sets the value of the endptId property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setEndptId(Long value) {
        this.endptId = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the ingressConfigStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIngressConfigStatus() {
        return ingressConfigStatus;
    }

    /**
     * Sets the value of the ingressConfigStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIngressConfigStatus(String value) {
        this.ingressConfigStatus = value;
    }

    /**
     * Gets the value of the egressConfigStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEgressConfigStatus() {
        return egressConfigStatus;
    }

    /**
     * Sets the value of the egressConfigStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEgressConfigStatus(String value) {
        this.egressConfigStatus = value;
    }

    /**
     * Gets the value of the accessType property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccessType() {
        return accessType;
    }

    /**
     * Sets the value of the accessType property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccessType(String value) {
        this.accessType = value;
    }

    /**
     * Gets the value of the ingressSelector property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIngressSelector() {
        return ingressSelector;
    }

    /**
     * Sets the value of the ingressSelector property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIngressSelector(String value) {
        this.ingressSelector = value;
    }

    /**
     * Gets the value of the ingressSelectorPresent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getIngressSelectorPresent() {
        return ingressSelectorPresent;
    }

    /**
     * Sets the value of the ingressSelectorPresent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIngressSelectorPresent(String value) {
        this.ingressSelectorPresent = value;
    }

    /**
     * Gets the value of the egressSelectorPresent property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEgressSelectorPresent() {
        return egressSelectorPresent;
    }

    /**
     * Sets the value of the egressSelectorPresent property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEgressSelectorPresent(String value) {
        this.egressSelectorPresent = value;
    }

    /**
     * Gets the value of the owner property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the createdByMgmt property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCreatedByMgmt() {
        return createdByMgmt;
    }

    /**
     * Sets the value of the createdByMgmt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCreatedByMgmt(String value) {
        this.createdByMgmt = value;
    }

    /**
     * Gets the value of the othersPermission property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOthersPermission() {
        return othersPermission;
    }

    /**
     * Sets the value of the othersPermission property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOthersPermission(String value) {
        this.othersPermission = value;
    }

    /**
     * Gets the value of the destination property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the quota property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getQuota() {
        return quota;
    }

    /**
     * Sets the value of the quota property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setQuota(BigInteger value) {
        this.quota = value;
    }

    /**
     * Gets the value of the respectMessagePriority property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRespectMessagePriority() {
        return respectMessagePriority;
    }

    /**
     * Sets the value of the respectMessagePriority property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRespectMessagePriority(String value) {
        this.respectMessagePriority = value;
    }

    /**
     * Gets the value of the respectTtl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRespectTtl() {
        return respectTtl;
    }

    /**
     * Sets the value of the respectTtl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRespectTtl(String value) {
        this.respectTtl = value;
    }

    /**
     * Gets the value of the maxTtl property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMaxTtl() {
        return maxTtl;
    }

    /**
     * Sets the value of the maxTtl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMaxTtl(String value) {
        this.maxTtl = value;
    }

    /**
     * Gets the value of the deadMessageQueue property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDeadMessageQueue() {
        return deadMessageQueue;
    }

    /**
     * Sets the value of the deadMessageQueue property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDeadMessageQueue(String value) {
        this.deadMessageQueue = value;
    }

    /**
     * Gets the value of the rejectMsgToSenderOnDiscard property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRejectMsgToSenderOnDiscard() {
        return rejectMsgToSenderOnDiscard;
    }

    /**
     * Sets the value of the rejectMsgToSenderOnDiscard property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRejectMsgToSenderOnDiscard(String value) {
        this.rejectMsgToSenderOnDiscard = value;
    }

    /**
     * Gets the value of the rejectMsgToSenderOnDiscardIncludingWhenShutdown property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRejectMsgToSenderOnDiscardIncludingWhenShutdown() {
        return rejectMsgToSenderOnDiscardIncludingWhenShutdown;
    }

    /**
     * Sets the value of the rejectMsgToSenderOnDiscardIncludingWhenShutdown property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRejectMsgToSenderOnDiscardIncludingWhenShutdown(String value) {
        this.rejectMsgToSenderOnDiscardIncludingWhenShutdown = value;
    }

    /**
     * Gets the value of the bindTimeForwardingMode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBindTimeForwardingMode() {
        return bindTimeForwardingMode;
    }

    /**
     * Sets the value of the bindTimeForwardingMode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBindTimeForwardingMode(String value) {
        this.bindTimeForwardingMode = value;
    }

    /**
     * Gets the value of the numMessagesSpooled property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNumMessagesSpooled() {
        return numMessagesSpooled;
    }

    /**
     * Sets the value of the numMessagesSpooled property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNumMessagesSpooled(BigInteger value) {
        this.numMessagesSpooled = value;
    }

    /**
     * Gets the value of the currentSpoolUsageInMb property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getCurrentSpoolUsageInMb() {
        return currentSpoolUsageInMb;
    }

    /**
     * Sets the value of the currentSpoolUsageInMb property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setCurrentSpoolUsageInMb(Double value) {
        this.currentSpoolUsageInMb = value;
    }

    /**
     * Gets the value of the highWaterMarkInMb property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getHighWaterMarkInMb() {
        return highWaterMarkInMb;
    }

    /**
     * Sets the value of the highWaterMarkInMb property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setHighWaterMarkInMb(Double value) {
        this.highWaterMarkInMb = value;
    }

    /**
     * Gets the value of the totalDeliveredUnackedMsgs property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getTotalDeliveredUnackedMsgs() {
        return totalDeliveredUnackedMsgs;
    }

    /**
     * Sets the value of the totalDeliveredUnackedMsgs property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setTotalDeliveredUnackedMsgs(BigInteger value) {
        this.totalDeliveredUnackedMsgs = value;
    }

    /**
     * Gets the value of the maxDeliveredUnackedMsgsPerFlow property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMaxDeliveredUnackedMsgsPerFlow() {
        return maxDeliveredUnackedMsgsPerFlow;
    }

    /**
     * Sets the value of the maxDeliveredUnackedMsgsPerFlow property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMaxDeliveredUnackedMsgsPerFlow(BigInteger value) {
        this.maxDeliveredUnackedMsgsPerFlow = value;
    }

    /**
     * Gets the value of the totalAckedMsgsInProgress property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getTotalAckedMsgsInProgress() {
        return totalAckedMsgsInProgress;
    }

    /**
     * Sets the value of the totalAckedMsgsInProgress property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setTotalAckedMsgsInProgress(BigInteger value) {
        this.totalAckedMsgsInProgress = value;
    }

    /**
     * Gets the value of the maxRedelivery property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMaxRedelivery() {
        return maxRedelivery;
    }

    /**
     * Sets the value of the maxRedelivery property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMaxRedelivery(BigInteger value) {
        this.maxRedelivery = value;
    }

    /**
     * Gets the value of the consumerAckPropagation property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConsumerAckPropagation() {
        return consumerAckPropagation;
    }

    /**
     * Sets the value of the consumerAckPropagation property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConsumerAckPropagation(String value) {
        this.consumerAckPropagation = value;
    }

    /**
     * Gets the value of the rejectLowPriorityMsg property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRejectLowPriorityMsg() {
        return rejectLowPriorityMsg;
    }

    /**
     * Sets the value of the rejectLowPriorityMsg property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRejectLowPriorityMsg(String value) {
        this.rejectLowPriorityMsg = value;
    }

    /**
     * Gets the value of the rejectLowPriorityMsgLimit property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getRejectLowPriorityMsgLimit() {
        return rejectLowPriorityMsgLimit;
    }

    /**
     * Sets the value of the rejectLowPriorityMsgLimit property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setRejectLowPriorityMsgLimit(BigInteger value) {
        this.rejectLowPriorityMsgLimit = value;
    }

    /**
     * Gets the value of the lowPriorityMsgCongestionState property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLowPriorityMsgCongestionState() {
        return lowPriorityMsgCongestionState;
    }

    /**
     * Sets the value of the lowPriorityMsgCongestionState property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLowPriorityMsgCongestionState(String value) {
        this.lowPriorityMsgCongestionState = value;
    }

    /**
     * Gets the value of the maxMessageSize property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMaxMessageSize() {
        return maxMessageSize;
    }

    /**
     * Sets the value of the maxMessageSize property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMaxMessageSize(BigInteger value) {
        this.maxMessageSize = value;
    }

    /**
     * Gets the value of the oldestMsgId property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getOldestMsgId() {
        return oldestMsgId;
    }

    /**
     * Sets the value of the oldestMsgId property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setOldestMsgId(BigInteger value) {
        this.oldestMsgId = value;
    }

    /**
     * Gets the value of the newestMsgId property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getNewestMsgId() {
        return newestMsgId;
    }

    /**
     * Sets the value of the newestMsgId property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setNewestMsgId(BigInteger value) {
        this.newestMsgId = value;
    }

    /**
     * Gets the value of the bindCount property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBindCount() {
        return bindCount;
    }

    /**
     * Sets the value of the bindCount property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBindCount(Long value) {
        this.bindCount = value;
    }

    /**
     * Gets the value of the bindCountThresholdHigh property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBindCountThresholdHigh() {
        return bindCountThresholdHigh;
    }

    /**
     * Sets the value of the bindCountThresholdHigh property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBindCountThresholdHigh(Long value) {
        this.bindCountThresholdHigh = value;
    }

    /**
     * Gets the value of the bindCountThresholdHighClear property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBindCountThresholdHighClear() {
        return bindCountThresholdHighClear;
    }

    /**
     * Sets the value of the bindCountThresholdHighClear property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBindCountThresholdHighClear(Long value) {
        this.bindCountThresholdHighClear = value;
    }

    /**
     * Gets the value of the bindCountThresholdHighPercentage property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBindCountThresholdHighPercentage() {
        return bindCountThresholdHighPercentage;
    }

    /**
     * Sets the value of the bindCountThresholdHighPercentage property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBindCountThresholdHighPercentage(Long value) {
        this.bindCountThresholdHighPercentage = value;
    }

    /**
     * Gets the value of the bindCountThresholdHighClearPercentage property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getBindCountThresholdHighClearPercentage() {
        return bindCountThresholdHighClearPercentage;
    }

    /**
     * Sets the value of the bindCountThresholdHighClearPercentage property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setBindCountThresholdHighClearPercentage(Long value) {
        this.bindCountThresholdHighClearPercentage = value;
    }

    /**
     * Gets the value of the maxBindCount property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getMaxBindCount() {
        return maxBindCount;
    }

    /**
     * Sets the value of the maxBindCount property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setMaxBindCount(Long value) {
        this.maxBindCount = value;
    }

    /**
     * Gets the value of the operationalMaxBindCount property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getOperationalMaxBindCount() {
        return operationalMaxBindCount;
    }

    /**
     * Sets the value of the operationalMaxBindCount property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setOperationalMaxBindCount(Long value) {
        this.operationalMaxBindCount = value;
    }

    /**
     * Gets the value of the topicSubscriptionCount property.
     *
     * @return possible object is
     * {@link Long }
     */
    public Long getTopicSubscriptionCount() {
        return topicSubscriptionCount;
    }

    /**
     * Sets the value of the topicSubscriptionCount property.
     *
     * @param value allowed object is
     *              {@link Long }
     */
    public void setTopicSubscriptionCount(Long value) {
        this.topicSubscriptionCount = value;
    }

    /**
     * Gets the value of the networkTopic property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNetworkTopic() {
        return networkTopic;
    }

    /**
     * Sets the value of the networkTopic property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNetworkTopic(String value) {
        this.networkTopic = value;
    }

    /**
     * Gets the value of the clients property.
     *
     * @return possible object is
     * {@link QendptInfoType.Clients }
     */
    public QendptInfoType.Clients getClients() {
        return clients;
    }

    /**
     * Sets the value of the clients property.
     *
     * @param value allowed object is
     *              {@link QendptInfoType.Clients }
     */
    public void setClients(QendptInfoType.Clients value) {
        this.clients = value;
    }

    /**
     * Gets the value of the event property.
     *
     * @return possible object is
     * {@link QendptInfoType.Event }
     */
    public QendptInfoType.Event getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     *
     * @param value allowed object is
     *              {@link QendptInfoType.Event }
     */
    public void setEvent(QendptInfoType.Event value) {
        this.event = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="client" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="is-active" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status-updates" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="deliver-from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="flow-state-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="no-local-delivery" type="{}yes-no-type" minOccurs="0"/>
     *                   &lt;element name="request-redelivery" type="{}yes-no-type" minOccurs="0"/>
     *                   &lt;element name="egress-selector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="window-size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="connect-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="activation-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="flow-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
     *                   &lt;element name="last-msg-id-delivered" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "client"
    })
    public static class Clients {

        protected List<QendptInfoType.Clients.Client> client;

        /**
         * Gets the value of the client property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the client property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClient().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QendptInfoType.Clients.Client }
         */
        public List<QendptInfoType.Clients.Client> getClient() {
            if (client == null) {
                client = new ArrayList<QendptInfoType.Clients.Client>();
            }
            return this.client;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="is-active" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status-updates" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="deliver-from" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="flow-state-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="no-local-delivery" type="{}yes-no-type" minOccurs="0"/>
         *         &lt;element name="request-redelivery" type="{}yes-no-type" minOccurs="0"/>
         *         &lt;element name="egress-selector" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="window-size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="connect-time" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="activation-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="flow-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
         *         &lt;element name="last-msg-id-delivered" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Client {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(name = "is-active", required = true)
            protected String isActive;
            @XmlElement(name = "status-updates")
            protected String statusUpdates;
            @XmlElement(name = "deliver-from")
            protected String deliverFrom;
            @XmlElement(name = "flow-state-reason")
            protected String flowStateReason;
            @XmlElement(name = "no-local-delivery")
            protected String noLocalDelivery;
            @XmlElement(name = "request-redelivery")
            protected String requestRedelivery;
            @XmlElement(name = "egress-selector")
            protected String egressSelector;
            @XmlElement(name = "window-size", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger windowSize;
            @XmlElement(name = "connect-time", required = true)
            protected String connectTime;
            @XmlElement(name = "activation-time")
            protected String activationTime;
            @XmlElement(name = "flow-id")
            @XmlSchemaType(name = "unsignedInt")
            protected Long flowId;
            @XmlElement(name = "last-msg-id-delivered")
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger lastMsgIdDelivered;

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the isActive property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIsActive() {
                return isActive;
            }

            /**
             * Sets the value of the isActive property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIsActive(String value) {
                this.isActive = value;
            }

            /**
             * Gets the value of the statusUpdates property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getStatusUpdates() {
                return statusUpdates;
            }

            /**
             * Sets the value of the statusUpdates property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setStatusUpdates(String value) {
                this.statusUpdates = value;
            }

            /**
             * Gets the value of the deliverFrom property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getDeliverFrom() {
                return deliverFrom;
            }

            /**
             * Sets the value of the deliverFrom property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setDeliverFrom(String value) {
                this.deliverFrom = value;
            }

            /**
             * Gets the value of the flowStateReason property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getFlowStateReason() {
                return flowStateReason;
            }

            /**
             * Sets the value of the flowStateReason property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setFlowStateReason(String value) {
                this.flowStateReason = value;
            }

            /**
             * Gets the value of the noLocalDelivery property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getNoLocalDelivery() {
                return noLocalDelivery;
            }

            /**
             * Sets the value of the noLocalDelivery property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setNoLocalDelivery(String value) {
                this.noLocalDelivery = value;
            }

            /**
             * Gets the value of the requestRedelivery property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getRequestRedelivery() {
                return requestRedelivery;
            }

            /**
             * Sets the value of the requestRedelivery property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setRequestRedelivery(String value) {
                this.requestRedelivery = value;
            }

            /**
             * Gets the value of the egressSelector property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getEgressSelector() {
                return egressSelector;
            }

            /**
             * Sets the value of the egressSelector property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setEgressSelector(String value) {
                this.egressSelector = value;
            }

            /**
             * Gets the value of the windowSize property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getWindowSize() {
                return windowSize;
            }

            /**
             * Sets the value of the windowSize property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setWindowSize(BigInteger value) {
                this.windowSize = value;
            }

            /**
             * Gets the value of the connectTime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getConnectTime() {
                return connectTime;
            }

            /**
             * Sets the value of the connectTime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setConnectTime(String value) {
                this.connectTime = value;
            }

            /**
             * Gets the value of the activationTime property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getActivationTime() {
                return activationTime;
            }

            /**
             * Sets the value of the activationTime property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setActivationTime(String value) {
                this.activationTime = value;
            }

            /**
             * Gets the value of the flowId property.
             *
             * @return possible object is
             * {@link Long }
             */
            public Long getFlowId() {
                return flowId;
            }

            /**
             * Sets the value of the flowId property.
             *
             * @param value allowed object is
             *              {@link Long }
             */
            public void setFlowId(Long value) {
                this.flowId = value;
            }

            /**
             * Gets the value of the lastMsgIdDelivered property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getLastMsgIdDelivered() {
                return lastMsgIdDelivered;
            }

            /**
             * Sets the value of the lastMsgIdDelivered property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setLastMsgIdDelivered(BigInteger value) {
                this.lastMsgIdDelivered = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="event-thresholds" type="{}event-thresholds" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "eventThresholds"
    })
    public static class Event {

        @XmlElement(name = "event-thresholds")
        protected List<EventThresholds> eventThresholds;

        /**
         * Gets the value of the eventThresholds property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eventThresholds property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEventThresholds().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EventThresholds }
         */
        public List<EventThresholds> getEventThresholds() {
            if (eventThresholds == null) {
                eventThresholds = new ArrayList<EventThresholds>();
            }
            return this.eventThresholds;
        }

    }

}
