//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for redundancy-mismatch-info-type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="redundancy-mismatch-info-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="primary-cvrid" type="{}ip-address-only"/>
 *         &lt;element name="backup-cvrid" type="{}ip-address-only"/>
 *         &lt;element name="mate-address" type="{}ip-address-only"/>
 *         &lt;element name="ad-enabled-cvrid" type="{}ip-address-only"/>
 *         &lt;element name="disk-wwn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redundancy-mismatch-info-type", propOrder = {
        "primaryCvrid",
        "backupCvrid",
        "mateAddress",
        "adEnabledCvrid",
        "diskWwn"
})
public class RedundancyMismatchInfoType {

    @XmlElement(name = "primary-cvrid", required = true)
    protected IpAddressOnly primaryCvrid;
    @XmlElement(name = "backup-cvrid", required = true)
    protected IpAddressOnly backupCvrid;
    @XmlElement(name = "mate-address", required = true)
    protected IpAddressOnly mateAddress;
    @XmlElement(name = "ad-enabled-cvrid", required = true)
    protected IpAddressOnly adEnabledCvrid;
    @XmlElement(name = "disk-wwn", required = true)
    protected String diskWwn;

    /**
     * Gets the value of the primaryCvrid property.
     *
     * @return possible object is
     * {@link IpAddressOnly }
     */
    public IpAddressOnly getPrimaryCvrid() {
        return primaryCvrid;
    }

    /**
     * Sets the value of the primaryCvrid property.
     *
     * @param value allowed object is
     *              {@link IpAddressOnly }
     */
    public void setPrimaryCvrid(IpAddressOnly value) {
        this.primaryCvrid = value;
    }

    /**
     * Gets the value of the backupCvrid property.
     *
     * @return possible object is
     * {@link IpAddressOnly }
     */
    public IpAddressOnly getBackupCvrid() {
        return backupCvrid;
    }

    /**
     * Sets the value of the backupCvrid property.
     *
     * @param value allowed object is
     *              {@link IpAddressOnly }
     */
    public void setBackupCvrid(IpAddressOnly value) {
        this.backupCvrid = value;
    }

    /**
     * Gets the value of the mateAddress property.
     *
     * @return possible object is
     * {@link IpAddressOnly }
     */
    public IpAddressOnly getMateAddress() {
        return mateAddress;
    }

    /**
     * Sets the value of the mateAddress property.
     *
     * @param value allowed object is
     *              {@link IpAddressOnly }
     */
    public void setMateAddress(IpAddressOnly value) {
        this.mateAddress = value;
    }

    /**
     * Gets the value of the adEnabledCvrid property.
     *
     * @return possible object is
     * {@link IpAddressOnly }
     */
    public IpAddressOnly getAdEnabledCvrid() {
        return adEnabledCvrid;
    }

    /**
     * Sets the value of the adEnabledCvrid property.
     *
     * @param value allowed object is
     *              {@link IpAddressOnly }
     */
    public void setAdEnabledCvrid(IpAddressOnly value) {
        this.adEnabledCvrid = value;
    }

    /**
     * Gets the value of the diskWwn property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDiskWwn() {
        return diskWwn;
    }

    /**
     * Sets the value of the diskWwn property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDiskWwn(String value) {
        this.diskWwn = value;
    }

}
