//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replay-stats complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="replay-stats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="replays-initiated" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="replays-succeeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="replays-failed" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="messages-replayed" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="replayed-messages-acked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replay-stats", propOrder = {

})
public class ReplayStats {

    @XmlElement(name = "replays-initiated", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysInitiated;
    @XmlElement(name = "replays-succeeded", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysSucceeded;
    @XmlElement(name = "replays-failed", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysFailed;
    @XmlElement(name = "messages-replayed", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger messagesReplayed;
    @XmlElement(name = "replayed-messages-acked", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replayedMessagesAcked;

    /**
     * Gets the value of the replaysInitiated property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReplaysInitiated() {
        return replaysInitiated;
    }

    /**
     * Sets the value of the replaysInitiated property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReplaysInitiated(BigInteger value) {
        this.replaysInitiated = value;
    }

    /**
     * Gets the value of the replaysSucceeded property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReplaysSucceeded() {
        return replaysSucceeded;
    }

    /**
     * Sets the value of the replaysSucceeded property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReplaysSucceeded(BigInteger value) {
        this.replaysSucceeded = value;
    }

    /**
     * Gets the value of the replaysFailed property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReplaysFailed() {
        return replaysFailed;
    }

    /**
     * Sets the value of the replaysFailed property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReplaysFailed(BigInteger value) {
        this.replaysFailed = value;
    }

    /**
     * Gets the value of the messagesReplayed property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getMessagesReplayed() {
        return messagesReplayed;
    }

    /**
     * Sets the value of the messagesReplayed property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setMessagesReplayed(BigInteger value) {
        this.messagesReplayed = value;
    }

    /**
     * Gets the value of the replayedMessagesAcked property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getReplayedMessagesAcked() {
        return replayedMessagesAcked;
    }

    /**
     * Sets the value of the replayedMessagesAcked property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setReplayedMessagesAcked(BigInteger value) {
        this.replayedMessagesAcked = value;
    }

}
