//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replay-state complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="replay-state">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="replay-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-replayed-message-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-replay-start-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-replay-complete-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-replay-failure-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last-replay-failure-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replay-state", propOrder = {
        "replayState",
        "lastReplayedMessageTime",
        "lastReplayStartTime",
        "lastReplayCompleteTime",
        "lastReplayFailureTime",
        "lastReplayFailureReason"
})
public class ReplayState {

    @XmlElement(name = "replay-state")
    protected String replayState;
    @XmlElement(name = "last-replayed-message-time")
    protected String lastReplayedMessageTime;
    @XmlElement(name = "last-replay-start-time")
    protected String lastReplayStartTime;
    @XmlElement(name = "last-replay-complete-time")
    protected String lastReplayCompleteTime;
    @XmlElement(name = "last-replay-failure-time")
    protected String lastReplayFailureTime;
    @XmlElement(name = "last-replay-failure-reason")
    protected String lastReplayFailureReason;

    /**
     * Gets the value of the replayState property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReplayState() {
        return replayState;
    }

    /**
     * Sets the value of the replayState property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReplayState(String value) {
        this.replayState = value;
    }

    /**
     * Gets the value of the lastReplayedMessageTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastReplayedMessageTime() {
        return lastReplayedMessageTime;
    }

    /**
     * Sets the value of the lastReplayedMessageTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastReplayedMessageTime(String value) {
        this.lastReplayedMessageTime = value;
    }

    /**
     * Gets the value of the lastReplayStartTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastReplayStartTime() {
        return lastReplayStartTime;
    }

    /**
     * Sets the value of the lastReplayStartTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastReplayStartTime(String value) {
        this.lastReplayStartTime = value;
    }

    /**
     * Gets the value of the lastReplayCompleteTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastReplayCompleteTime() {
        return lastReplayCompleteTime;
    }

    /**
     * Sets the value of the lastReplayCompleteTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastReplayCompleteTime(String value) {
        this.lastReplayCompleteTime = value;
    }

    /**
     * Gets the value of the lastReplayFailureTime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastReplayFailureTime() {
        return lastReplayFailureTime;
    }

    /**
     * Sets the value of the lastReplayFailureTime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastReplayFailureTime(String value) {
        this.lastReplayFailureTime = value;
    }

    /**
     * Gets the value of the lastReplayFailureReason property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLastReplayFailureReason() {
        return lastReplayFailureReason;
    }

    /**
     * Sets the value of the lastReplayFailureReason property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLastReplayFailureReason(String value) {
        this.lastReplayFailureReason = value;
    }

}
