//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replication-vpn-stats complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="replication-vpn-stats">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="active-stats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="message-processing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="sync-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="sync-msgs-queued-to-standby-as-async" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="async-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="promoted-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="pruned-locally-consumed-msgs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="sync-replication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="transitions-to-ineligible" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="ineligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
 *                             &lt;element name="eligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
 *                             &lt;element name="mate-flow-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
 *                             &lt;element name="mate-flow-not-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ack-propagation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="msgs-tx-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="rec-req-from-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="standby-stats">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="message-processing">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="msgs-rx-from-active" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ack-propagation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="ack-prop-msgs-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="recon-req-tx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="out-of-seq-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="transaction-replication">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="transaction-requests" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-success" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-success-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-success-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-success-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-fail" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-fail-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-fail-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                             &lt;element name="transaction-requests-fail-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replication-vpn-stats", propOrder = {
        "activeStats",
        "standbyStats"
})
public class ReplicationVpnStats {

    @XmlElement(name = "active-stats", required = true)
    protected ReplicationVpnStats.ActiveStats activeStats;
    @XmlElement(name = "standby-stats", required = true)
    protected ReplicationVpnStats.StandbyStats standbyStats;

    /**
     * Gets the value of the activeStats property.
     *
     * @return possible object is
     * {@link ReplicationVpnStats.ActiveStats }
     */
    public ReplicationVpnStats.ActiveStats getActiveStats() {
        return activeStats;
    }

    /**
     * Sets the value of the activeStats property.
     *
     * @param value allowed object is
     *              {@link ReplicationVpnStats.ActiveStats }
     */
    public void setActiveStats(ReplicationVpnStats.ActiveStats value) {
        this.activeStats = value;
    }

    /**
     * Gets the value of the standbyStats property.
     *
     * @return possible object is
     * {@link ReplicationVpnStats.StandbyStats }
     */
    public ReplicationVpnStats.StandbyStats getStandbyStats() {
        return standbyStats;
    }

    /**
     * Sets the value of the standbyStats property.
     *
     * @param value allowed object is
     *              {@link ReplicationVpnStats.StandbyStats }
     */
    public void setStandbyStats(ReplicationVpnStats.StandbyStats value) {
        this.standbyStats = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="message-processing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="sync-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="sync-msgs-queued-to-standby-as-async" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="async-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="promoted-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="pruned-locally-consumed-msgs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="sync-replication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="transitions-to-ineligible" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="ineligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
     *                   &lt;element name="eligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
     *                   &lt;element name="mate-flow-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
     *                   &lt;element name="mate-flow-not-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ack-propagation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="msgs-tx-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="rec-req-from-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class ActiveStats {

        @XmlElement(name = "message-processing", required = true)
        protected ReplicationVpnStats.ActiveStats.MessageProcessing messageProcessing;
        @XmlElement(name = "sync-replication", required = true)
        protected ReplicationVpnStats.ActiveStats.SyncReplication syncReplication;
        @XmlElement(name = "ack-propagation", required = true)
        protected ReplicationVpnStats.ActiveStats.AckPropagation ackPropagation;

        /**
         * Gets the value of the messageProcessing property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.ActiveStats.MessageProcessing }
         */
        public ReplicationVpnStats.ActiveStats.MessageProcessing getMessageProcessing() {
            return messageProcessing;
        }

        /**
         * Sets the value of the messageProcessing property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.ActiveStats.MessageProcessing }
         */
        public void setMessageProcessing(ReplicationVpnStats.ActiveStats.MessageProcessing value) {
            this.messageProcessing = value;
        }

        /**
         * Gets the value of the syncReplication property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.ActiveStats.SyncReplication }
         */
        public ReplicationVpnStats.ActiveStats.SyncReplication getSyncReplication() {
            return syncReplication;
        }

        /**
         * Sets the value of the syncReplication property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.ActiveStats.SyncReplication }
         */
        public void setSyncReplication(ReplicationVpnStats.ActiveStats.SyncReplication value) {
            this.syncReplication = value;
        }

        /**
         * Gets the value of the ackPropagation property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.ActiveStats.AckPropagation }
         */
        public ReplicationVpnStats.ActiveStats.AckPropagation getAckPropagation() {
            return ackPropagation;
        }

        /**
         * Sets the value of the ackPropagation property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.ActiveStats.AckPropagation }
         */
        public void setAckPropagation(ReplicationVpnStats.ActiveStats.AckPropagation value) {
            this.ackPropagation = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="msgs-tx-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="rec-req-from-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AckPropagation {

            @XmlElement(name = "msgs-tx-to-standby", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger msgsTxToStandby;
            @XmlElement(name = "rec-req-from-standby", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger recReqFromStandby;

            /**
             * Gets the value of the msgsTxToStandby property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getMsgsTxToStandby() {
                return msgsTxToStandby;
            }

            /**
             * Sets the value of the msgsTxToStandby property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setMsgsTxToStandby(BigInteger value) {
                this.msgsTxToStandby = value;
            }

            /**
             * Gets the value of the recReqFromStandby property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getRecReqFromStandby() {
                return recReqFromStandby;
            }

            /**
             * Sets the value of the recReqFromStandby property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setRecReqFromStandby(BigInteger value) {
                this.recReqFromStandby = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="sync-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="sync-msgs-queued-to-standby-as-async" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="async-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="promoted-msgs-queued-to-standby" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="pruned-locally-consumed-msgs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class MessageProcessing {

            @XmlElement(name = "sync-msgs-queued-to-standby", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger syncMsgsQueuedToStandby;
            @XmlElement(name = "sync-msgs-queued-to-standby-as-async", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger syncMsgsQueuedToStandbyAsAsync;
            @XmlElement(name = "async-msgs-queued-to-standby", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger asyncMsgsQueuedToStandby;
            @XmlElement(name = "promoted-msgs-queued-to-standby", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger promotedMsgsQueuedToStandby;
            @XmlElement(name = "pruned-locally-consumed-msgs", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger prunedLocallyConsumedMsgs;

            /**
             * Gets the value of the syncMsgsQueuedToStandby property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSyncMsgsQueuedToStandby() {
                return syncMsgsQueuedToStandby;
            }

            /**
             * Sets the value of the syncMsgsQueuedToStandby property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSyncMsgsQueuedToStandby(BigInteger value) {
                this.syncMsgsQueuedToStandby = value;
            }

            /**
             * Gets the value of the syncMsgsQueuedToStandbyAsAsync property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getSyncMsgsQueuedToStandbyAsAsync() {
                return syncMsgsQueuedToStandbyAsAsync;
            }

            /**
             * Sets the value of the syncMsgsQueuedToStandbyAsAsync property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setSyncMsgsQueuedToStandbyAsAsync(BigInteger value) {
                this.syncMsgsQueuedToStandbyAsAsync = value;
            }

            /**
             * Gets the value of the asyncMsgsQueuedToStandby property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getAsyncMsgsQueuedToStandby() {
                return asyncMsgsQueuedToStandby;
            }

            /**
             * Sets the value of the asyncMsgsQueuedToStandby property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setAsyncMsgsQueuedToStandby(BigInteger value) {
                this.asyncMsgsQueuedToStandby = value;
            }

            /**
             * Gets the value of the promotedMsgsQueuedToStandby property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getPromotedMsgsQueuedToStandby() {
                return promotedMsgsQueuedToStandby;
            }

            /**
             * Sets the value of the promotedMsgsQueuedToStandby property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setPromotedMsgsQueuedToStandby(BigInteger value) {
                this.promotedMsgsQueuedToStandby = value;
            }

            /**
             * Gets the value of the prunedLocallyConsumedMsgs property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getPrunedLocallyConsumedMsgs() {
                return prunedLocallyConsumedMsgs;
            }

            /**
             * Sets the value of the prunedLocallyConsumedMsgs property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setPrunedLocallyConsumedMsgs(BigInteger value) {
                this.prunedLocallyConsumedMsgs = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="transitions-to-ineligible" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="ineligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
         *         &lt;element name="eligible-high-water-mark" type="{}uptime-type" minOccurs="0"/>
         *         &lt;element name="mate-flow-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
         *         &lt;element name="mate-flow-not-congested-high-water-mark" type="{}uptime-type" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class SyncReplication {

            @XmlElement(name = "transitions-to-ineligible", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transitionsToIneligible;
            @XmlElement(name = "ineligible-high-water-mark")
            protected UptimeType ineligibleHighWaterMark;
            @XmlElement(name = "eligible-high-water-mark")
            protected UptimeType eligibleHighWaterMark;
            @XmlElement(name = "mate-flow-congested-high-water-mark")
            protected UptimeType mateFlowCongestedHighWaterMark;
            @XmlElement(name = "mate-flow-not-congested-high-water-mark")
            protected UptimeType mateFlowNotCongestedHighWaterMark;

            /**
             * Gets the value of the transitionsToIneligible property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransitionsToIneligible() {
                return transitionsToIneligible;
            }

            /**
             * Sets the value of the transitionsToIneligible property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransitionsToIneligible(BigInteger value) {
                this.transitionsToIneligible = value;
            }

            /**
             * Gets the value of the ineligibleHighWaterMark property.
             *
             * @return possible object is
             * {@link UptimeType }
             */
            public UptimeType getIneligibleHighWaterMark() {
                return ineligibleHighWaterMark;
            }

            /**
             * Sets the value of the ineligibleHighWaterMark property.
             *
             * @param value allowed object is
             *              {@link UptimeType }
             */
            public void setIneligibleHighWaterMark(UptimeType value) {
                this.ineligibleHighWaterMark = value;
            }

            /**
             * Gets the value of the eligibleHighWaterMark property.
             *
             * @return possible object is
             * {@link UptimeType }
             */
            public UptimeType getEligibleHighWaterMark() {
                return eligibleHighWaterMark;
            }

            /**
             * Sets the value of the eligibleHighWaterMark property.
             *
             * @param value allowed object is
             *              {@link UptimeType }
             */
            public void setEligibleHighWaterMark(UptimeType value) {
                this.eligibleHighWaterMark = value;
            }

            /**
             * Gets the value of the mateFlowCongestedHighWaterMark property.
             *
             * @return possible object is
             * {@link UptimeType }
             */
            public UptimeType getMateFlowCongestedHighWaterMark() {
                return mateFlowCongestedHighWaterMark;
            }

            /**
             * Sets the value of the mateFlowCongestedHighWaterMark property.
             *
             * @param value allowed object is
             *              {@link UptimeType }
             */
            public void setMateFlowCongestedHighWaterMark(UptimeType value) {
                this.mateFlowCongestedHighWaterMark = value;
            }

            /**
             * Gets the value of the mateFlowNotCongestedHighWaterMark property.
             *
             * @return possible object is
             * {@link UptimeType }
             */
            public UptimeType getMateFlowNotCongestedHighWaterMark() {
                return mateFlowNotCongestedHighWaterMark;
            }

            /**
             * Sets the value of the mateFlowNotCongestedHighWaterMark property.
             *
             * @param value allowed object is
             *              {@link UptimeType }
             */
            public void setMateFlowNotCongestedHighWaterMark(UptimeType value) {
                this.mateFlowNotCongestedHighWaterMark = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="message-processing">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="msgs-rx-from-active" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ack-propagation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="ack-prop-msgs-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="recon-req-tx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="out-of-seq-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="transaction-replication">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="transaction-requests" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-success" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-success-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-success-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-success-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-fail" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-fail-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-fail-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                   &lt;element name="transaction-requests-fail-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class StandbyStats {

        @XmlElement(name = "message-processing", required = true)
        protected ReplicationVpnStats.StandbyStats.MessageProcessing messageProcessing;
        @XmlElement(name = "ack-propagation", required = true)
        protected ReplicationVpnStats.StandbyStats.AckPropagation ackPropagation;
        @XmlElement(name = "transaction-replication", required = true)
        protected ReplicationVpnStats.StandbyStats.TransactionReplication transactionReplication;

        /**
         * Gets the value of the messageProcessing property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.StandbyStats.MessageProcessing }
         */
        public ReplicationVpnStats.StandbyStats.MessageProcessing getMessageProcessing() {
            return messageProcessing;
        }

        /**
         * Sets the value of the messageProcessing property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.StandbyStats.MessageProcessing }
         */
        public void setMessageProcessing(ReplicationVpnStats.StandbyStats.MessageProcessing value) {
            this.messageProcessing = value;
        }

        /**
         * Gets the value of the ackPropagation property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.StandbyStats.AckPropagation }
         */
        public ReplicationVpnStats.StandbyStats.AckPropagation getAckPropagation() {
            return ackPropagation;
        }

        /**
         * Sets the value of the ackPropagation property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.StandbyStats.AckPropagation }
         */
        public void setAckPropagation(ReplicationVpnStats.StandbyStats.AckPropagation value) {
            this.ackPropagation = value;
        }

        /**
         * Gets the value of the transactionReplication property.
         *
         * @return possible object is
         * {@link ReplicationVpnStats.StandbyStats.TransactionReplication }
         */
        public ReplicationVpnStats.StandbyStats.TransactionReplication getTransactionReplication() {
            return transactionReplication;
        }

        /**
         * Sets the value of the transactionReplication property.
         *
         * @param value allowed object is
         *              {@link ReplicationVpnStats.StandbyStats.TransactionReplication }
         */
        public void setTransactionReplication(ReplicationVpnStats.StandbyStats.TransactionReplication value) {
            this.transactionReplication = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="ack-prop-msgs-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="recon-req-tx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="out-of-seq-rx" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class AckPropagation {

            @XmlElement(name = "ack-prop-msgs-rx", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger ackPropMsgsRx;
            @XmlElement(name = "recon-req-tx", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger reconReqTx;
            @XmlElement(name = "out-of-seq-rx", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger outOfSeqRx;

            /**
             * Gets the value of the ackPropMsgsRx property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getAckPropMsgsRx() {
                return ackPropMsgsRx;
            }

            /**
             * Sets the value of the ackPropMsgsRx property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setAckPropMsgsRx(BigInteger value) {
                this.ackPropMsgsRx = value;
            }

            /**
             * Gets the value of the reconReqTx property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getReconReqTx() {
                return reconReqTx;
            }

            /**
             * Sets the value of the reconReqTx property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setReconReqTx(BigInteger value) {
                this.reconReqTx = value;
            }

            /**
             * Gets the value of the outOfSeqRx property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getOutOfSeqRx() {
                return outOfSeqRx;
            }

            /**
             * Sets the value of the outOfSeqRx property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setOutOfSeqRx(BigInteger value) {
                this.outOfSeqRx = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="msgs-rx-from-active" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class MessageProcessing {

            @XmlElement(name = "msgs-rx-from-active", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger msgsRxFromActive;

            /**
             * Gets the value of the msgsRxFromActive property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getMsgsRxFromActive() {
                return msgsRxFromActive;
            }

            /**
             * Sets the value of the msgsRxFromActive property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setMsgsRxFromActive(BigInteger value) {
                this.msgsRxFromActive = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="transaction-requests" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-success" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-success-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-success-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-success-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-fail" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-fail-prepare" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-fail-commit" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *         &lt;element name="transaction-requests-fail-rollback" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class TransactionReplication {

            @XmlElement(name = "transaction-requests", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequests;
            @XmlElement(name = "transaction-requests-success", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsSuccess;
            @XmlElement(name = "transaction-requests-success-prepare", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsSuccessPrepare;
            @XmlElement(name = "transaction-requests-success-commit", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsSuccessCommit;
            @XmlElement(name = "transaction-requests-success-rollback", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsSuccessRollback;
            @XmlElement(name = "transaction-requests-fail", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsFail;
            @XmlElement(name = "transaction-requests-fail-prepare", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsFailPrepare;
            @XmlElement(name = "transaction-requests-fail-commit", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsFailCommit;
            @XmlElement(name = "transaction-requests-fail-rollback", required = true)
            @XmlSchemaType(name = "unsignedLong")
            protected BigInteger transactionRequestsFailRollback;

            /**
             * Gets the value of the transactionRequests property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequests() {
                return transactionRequests;
            }

            /**
             * Sets the value of the transactionRequests property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequests(BigInteger value) {
                this.transactionRequests = value;
            }

            /**
             * Gets the value of the transactionRequestsSuccess property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsSuccess() {
                return transactionRequestsSuccess;
            }

            /**
             * Sets the value of the transactionRequestsSuccess property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsSuccess(BigInteger value) {
                this.transactionRequestsSuccess = value;
            }

            /**
             * Gets the value of the transactionRequestsSuccessPrepare property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsSuccessPrepare() {
                return transactionRequestsSuccessPrepare;
            }

            /**
             * Sets the value of the transactionRequestsSuccessPrepare property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsSuccessPrepare(BigInteger value) {
                this.transactionRequestsSuccessPrepare = value;
            }

            /**
             * Gets the value of the transactionRequestsSuccessCommit property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsSuccessCommit() {
                return transactionRequestsSuccessCommit;
            }

            /**
             * Sets the value of the transactionRequestsSuccessCommit property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsSuccessCommit(BigInteger value) {
                this.transactionRequestsSuccessCommit = value;
            }

            /**
             * Gets the value of the transactionRequestsSuccessRollback property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsSuccessRollback() {
                return transactionRequestsSuccessRollback;
            }

            /**
             * Sets the value of the transactionRequestsSuccessRollback property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsSuccessRollback(BigInteger value) {
                this.transactionRequestsSuccessRollback = value;
            }

            /**
             * Gets the value of the transactionRequestsFail property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsFail() {
                return transactionRequestsFail;
            }

            /**
             * Sets the value of the transactionRequestsFail property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsFail(BigInteger value) {
                this.transactionRequestsFail = value;
            }

            /**
             * Gets the value of the transactionRequestsFailPrepare property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsFailPrepare() {
                return transactionRequestsFailPrepare;
            }

            /**
             * Sets the value of the transactionRequestsFailPrepare property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsFailPrepare(BigInteger value) {
                this.transactionRequestsFailPrepare = value;
            }

            /**
             * Gets the value of the transactionRequestsFailCommit property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsFailCommit() {
                return transactionRequestsFailCommit;
            }

            /**
             * Sets the value of the transactionRequestsFailCommit property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsFailCommit(BigInteger value) {
                this.transactionRequestsFailCommit = value;
            }

            /**
             * Gets the value of the transactionRequestsFailRollback property.
             *
             * @return possible object is
             * {@link BigInteger }
             */
            public BigInteger getTransactionRequestsFailRollback() {
                return transactionRequestsFailRollback;
            }

            /**
             * Sets the value of the transactionRequestsFailRollback property.
             *
             * @param value allowed object is
             *              {@link BigInteger }
             */
            public void setTransactionRequestsFailRollback(BigInteger value) {
                this.transactionRequestsFailRollback = value;
            }

        }

    }

}
