//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:13 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempReply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="serviceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="network" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="uptime" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clients" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="subscriptions" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="stats" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}solStatsType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceType", propOrder = {

})
public class ServiceType {

    @XmlElement(name = "service-id")
    protected String serviceId;
    protected String network;
    protected String uptime;
    protected Integer clients;
    protected Integer subscriptions;
    protected ServiceType.Stats stats;

    /**
     * Gets the value of the serviceId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the network property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNetwork() {
        return network;
    }

    /**
     * Sets the value of the network property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNetwork(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the uptime property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUptime() {
        return uptime;
    }

    /**
     * Sets the value of the uptime property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUptime(String value) {
        this.uptime = value;
    }

    /**
     * Gets the value of the clients property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getClients() {
        return clients;
    }

    /**
     * Sets the value of the clients property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setClients(Integer value) {
        this.clients = value;
    }

    /**
     * Gets the value of the subscriptions property.
     *
     * @return possible object is
     * {@link Integer }
     */
    public Integer getSubscriptions() {
        return subscriptions;
    }

    /**
     * Sets the value of the subscriptions property.
     *
     * @param value allowed object is
     *              {@link Integer }
     */
    public void setSubscriptions(Integer value) {
        this.subscriptions = value;
    }

    /**
     * Gets the value of the stats property.
     *
     * @return possible object is
     * {@link ServiceType.Stats }
     */
    public ServiceType.Stats getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     *
     * @param value allowed object is
     *              {@link ServiceType.Stats }
     */
    public void setStats(ServiceType.Stats value) {
        this.stats = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}solStatsType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Stats
            extends SolStatsType {


    }

}
