//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:51 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CMD_usernameMsgVpn_defaultAccessLevel_parameterType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CMD_usernameMsgVpn_defaultAccessLevel_parameterType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="read-only"/>
 *     &lt;enumeration value="read-write"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "CMD_usernameMsgVpn_defaultAccessLevel_parameterType")
@XmlEnum
public enum CMDUsernameMsgVpnDefaultAccessLevelParameterType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("read-only")
    READ_ONLY("read-only"),
    @XmlEnumValue("read-write")
    READ_WRITE("read-write");
    private final String value;

    CMDUsernameMsgVpnDefaultAccessLevelParameterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CMDUsernameMsgVpnDefaultAccessLevelParameterType fromValue(String v) {
        for (CMDUsernameMsgVpnDefaultAccessLevelParameterType c : CMDUsernameMsgVpnDefaultAccessLevelParameterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
