//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 09:27:51 AM GMT 
//


package com.solace.semp.sempv1.SolaceSempRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for USER_ACCESS_LEVEL_PARAM_DEPRECATED_LAST_USED_IN_D32.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="USER_ACCESS_LEVEL_PARAM_DEPRECATED_LAST_USED_IN_D32">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="read-only"/>
 *     &lt;enumeration value="read-write"/>
 *     &lt;enumeration value="admin"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "USER_ACCESS_LEVEL_PARAM_DEPRECATED_LAST_USED_IN_D32")
@XmlEnum
public enum USERACCESSLEVELPARAMDEPRECATEDLASTUSEDIND32 {

    @XmlEnumValue("read-only")
    READ_ONLY("read-only"),
    @XmlEnumValue("read-write")
    READ_WRITE("read-write"),
    @XmlEnumValue("admin")
    ADMIN("admin");
    private final String value;

    USERACCESSLEVELPARAMDEPRECATEDLASTUSEDIND32(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static USERACCESSLEVELPARAMDEPRECATEDLASTUSEDIND32 fromValue(String v) {
        for (USERACCESSLEVELPARAMDEPRECATEDLASTUSEDIND32 c : USERACCESSLEVELPARAMDEPRECATEDLASTUSEDIND32.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
